Repository bigbluebutton/greenlight, pull requests merged in 2019-06, with the labels that each got.

#580 GRN2-161: Removed env variable from name
  config/locales/en.yml
Labels: v2.1.2

#578 Fixed #568: Removed the Oops from the string (GRN2-160)
  config/locales/ar.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/es_MX.yml
  config/locales/fa_IR.yml
  config/locales/fr.yml
  config/locales/hu_HU.yml
  config/locales/it.yml
  config/locales/it_IT.yml
  config/locales/pt.yml
  config/locales/pt_BR.yml
  config/locales/ru_RU.yml
  config/locales/vi_VN.yml
  config/locales/zh_CN.yml
Labels: v2.1.2

#577 Fixed #558: Removed recording warning on room delete if there are no recordings (GRN2-157)
  app/views/shared/modals/_delete_room_modal.html.erb
  config/locales/en.yml
Labels: v2.1.2

#582 Improve container build: GRN2-156
  Dockerfile
  docker-compose.yml
  sample.env
  scripts/image_build.sh
Labels: v2.1.2

#579 Remove bn launcher: GRN2-107, GRN2-21
  Gemfile
  Gemfile.lock
  app/assets/images/saml-logo.png
  app/assets/stylesheets/main.scss
  app/controllers/sessions_controller.rb
  app/helpers/application_helper.rb
  app/helpers/sessions_helper.rb
  app/models/user.rb
  config/environments/production.rb
  config/initializers/omniauth.rb
  config/locales/ar.yml
  config/locales/de_DE.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/es_MX.yml
  config/locales/fr.yml
  config/locales/hi_IN.yml
  config/locales/pt.yml
  config/locales/pt_BR.yml
  config/locales/ru_RU.yml
  config/locales/zh_CN.yml
  sample.env
  spec/controllers/sessions_controller_spec.rb
  spec/models/user_spec.rb
Labels: v2.2

#589 GRN2-163: Fixed issue with user list
  app/controllers/admins_controller.rb
Labels: v2.1.3

#594 GRN2-162: Revert to sqlite in docker compose
  docker-compose.yml
  sample.env
Labels: v2.1.3
