Repository bigbluebutton/greenlight, pull requests merged in 2019-08, with the labels that each got.

#719 GRN2-xx: Fixed issue with recording row and added small fix to roles migration (Fixed #717, #718)
  app/assets/javascripts/user_edit.js
  app/controllers/application_controller.rb
  app/views/rooms/join.html.erb
  app/views/shared/components/_public_recording_row.html.erb
  app/views/shared/settings/_account.html.erb
  app/views/shared/settings/_setting_view.html.erb
  db/migrate/20190726153012_add_custom_roles.rb
Labels: v2.3

#721 Roles editor bug fix
  app/assets/stylesheets/rooms.scss
  app/controllers/recordings_controller.rb
  app/controllers/users_controller.rb
  app/views/rooms/cant_create_rooms.html.erb
  app/views/shared/settings/_account.html.erb
  config/locales/en.yml
  spec/controllers/users_controller_spec.rb
Labels: v2.3

#723 Improve can't create room view
  app/assets/stylesheets/rooms.scss
  app/controllers/rooms_controller.rb
  app/controllers/users_controller.rb
  app/mailers/user_mailer.rb
  app/views/rooms/cant_create_rooms.html.erb
  config/locales/en.yml
  test/mailers/previews/user_mailer_preview.rb
Labels: v2.3

#724 GRN2-xx: Fixed issue with invalid csrf token
  app/assets/javascripts/main.js
Labels: v2.3

#727 GRN2-xx: Fixed issue with room settings not showing updated values
  app/assets/javascripts/room.js.erb
  app/assets/javascripts/user_edit.js
  lib/tasks/user.rake
Labels: v2.3

#729 Bug fixes for roles
  app/controllers/admins_controller.rb
  app/mailers/user_mailer.rb
  app/models/role.rb
  app/models/user.rb
  app/views/admins/components/_roles.html.erb
  app/views/shared/settings/_account.html.erb
Labels: v2.3

#734 GRN2-xx: General bug fixes and performance upgrades
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.scss
  app/controllers/sessions_controller.rb
  app/views/application/migration_error.html.erb
  app/views/layouts/application.html.erb
  app/views/main/index.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_header.html.erb
  config/locales/en.yml
  vendor/assets/javascripts/pickr.min.js
  vendor/assets/javascripts/pickr.min.js.map
  vendor/assets/stylesheets/monolith.min.css
Labels: v2.3.1

#736 GRN2-xx: Refactored code related to all recordings pagination (Fixed #735)
  app/controllers/concerns/recorder.rb
Labels: v2.3.1

#737 GRN2-223: Added the ability for admins to send a reset password email for users
  app/controllers/admins_controller.rb
  app/controllers/password_resets_controller.rb
  app/helpers/application_helper.rb
  app/models/ability.rb
  app/views/shared/settings/_account.html.erb
  app/views/user_mailer/password_reset.html.erb
  app/views/user_mailer/password_reset.text.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/password_resets_controller_spec.rb
Labels: v2.3.1

#739 GRN2-224: Added event logs and production caching
  app/assets/stylesheets/application.scss
  app/controllers/account_activations_controller.rb
  app/controllers/admins_controller.rb
  app/controllers/password_resets_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/sessions_helper.rb
  config/environments/production.rb
  config/initializers/assets.rb
Labels: v2.3.1

#740 GRN2-224: Fixes for assets
  app/assets/stylesheets/application.scss
  config/environments/production.rb
  config/initializers/assets.rb
  vendor/assets/javascripts/pickr.min.js
  vendor/assets/javascripts/pickr.min.js.map
  vendor/assets/stylesheets/monolith.min.scss
Labels: v2.3.1

#745 GRN2-223: Added extra check for reset password
  app/helpers/application_helper.rb
Labels: v2.3.1

#749 GRN2-xx: Added ability to add Google Analytics tracker
  app/helpers/application_helper.rb
  app/views/layouts/application.html.erb
  config/application.rb
  sample.env
Labels: v2.3.2

#753 GRN2-225, GRN2-227: Images sent by Office365 Institutional accounts break the rooms
  app/helpers/application_helper.rb
  app/views/shared/_header.html.erb
  lib/tasks/migrate_old_office365_users.rake
Labels: v2.3.2

#755 GRN2-230: Cached request to provider to increase application performance
  app/controllers/admins_controller.rb
  app/views/admins/components/_settings.html.erb
  config/locales/en.yml
  config/routes.rb
  lib/bbb_api.rb
Labels: v2.3.2

#758 GRN2-229: Added a Maintenance Window flash
  app/assets/javascripts/cookies.js
  app/controllers/application_controller.rb
  app/views/shared/_flash_messages.html.erb
  config/application.rb
  config/locales/en.yml
  sample.env
Labels: v2.3.2

#761 GRN2-230: Switched to Redis cache in production
  Gemfile
  Gemfile.lock
  config/environments/production.rb
Labels: v2.3.2

#776 GRN2-xx: Migration Error now returns 500 and added the option to disable cache
  app/controllers/application_controller.rb
  config/application.rb
  lib/bbb_api.rb
Labels: v2.3.3

#777 GRN2-xx: Allowed room access text to be translated (Fixed #775)
  app/assets/javascripts/room.js.erb
Labels: v2.3.3

#780 GRN2-xx: Cleaning up bugs that appeared after refactoring
  app/assets/javascripts/rename.js
  app/controllers/concerns/authenticator.rb
  app/controllers/rooms_controller.rb
Labels: v2.4
