Repository bigbluebutton/greenlight, pull requests merged in 2019-07, with the labels that each got.

#600 GRN2-165: Added functionality to bypass launcher
  Gemfile
  Gemfile.lock
  app/assets/images/saml-logo.png
  app/assets/stylesheets/main.scss
  app/controllers/sessions_controller.rb
  app/helpers/application_helper.rb
  app/helpers/sessions_helper.rb
  app/models/user.rb
  config/environments/production.rb
  config/initializers/omniauth.rb
  config/locales/ar.yml
  config/locales/de_DE.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/es_MX.yml
  config/locales/fr.yml
  config/locales/hi_IN.yml
  config/locales/pt.yml
  config/locales/pt_BR.yml
  config/locales/ru_RU.yml
  config/locales/zh_CN.yml
  sample.env
  spec/controllers/sessions_controller_spec.rb
  spec/models/user_spec.rb
Labels: v2.2

#602 GRN2-166: Fixed issue with language fallback not working (Fixed #593)
  app/views/rooms/show.html.erb
  app/views/shared/components/_room_block.html.erb
  config/application.rb
  config/environments/production.rb
  config/initializers/languages.rb
Labels: v2.2

#603 GRN2-167: Removed duplicate keys in en.yml file (Fixes #584)
  app/views/user_mailer/invite_email.html.erb
  app/views/user_mailer/invite_email.text.erb
  config/locales/en.yml
Labels: v2.2

#604 GRN2-171: Added the missing model attribute strings (Fixed #596)
  config/locales/en.yml
Labels: v2.2

#610 GRN2-135: Limit Jquery version in Gemfile
  Gemfile
  Gemfile.lock
Labels: v2.2

#611 GRN2-152: Added a max-width to the email column in the manage users table
  app/assets/stylesheets/admins.scss
  app/views/shared/admin_settings/_users.html.erb
Labels: v2.2

#607 GRN2-168: Added setting for admin to limit the number of rooms for the user (Fixed #341)
  app/assets/stylesheets/admins.scss
  app/controllers/admins_controller.rb
  app/controllers/rooms_controller.rb
  app/helpers/admins_helper.rb
  app/helpers/rooms_helper.rb
  app/models/setting.rb
  app/views/rooms/show.html.erb
  app/views/shared/admin_settings/_site_settings.html.erb
  config/application.rb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/admins_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v2.2

#609 GRN2-174: Added 404 if user does not exist
  app/controllers/application_controller.rb
  app/views/errors/not_found.html.erb
  config/locales/en.yml
  spec/controllers/application_controller_spec.rb
Labels: v2.2

#613 GRN2-178: Generalized use of language_name based on Mozilla Mapping
  Gemfile
  Gemfile.lock
  app/helpers/application_helper.rb
  config/locales/ar.yml
  config/locales/de_DE.yml
  config/locales/el.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/es_MX.yml
  config/locales/fa_IR.yml
  config/locales/fr.yml
  config/locales/hi_IN.yml
  config/locales/hu_HU.yml
  config/locales/it.yml
  config/locales/it_IT.yml
  config/locales/pt.yml
  config/locales/pt_BR.yml
  config/locales/ru_RU.yml
  config/locales/vi_VN.yml
  config/locales/zh_CN.yml
Labels: v2.2

#615 GRN2-155: Begin preparing for removal of Twitter accounts
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/helpers/sessions_helper.rb
  app/views/shared/_flash_messages.html.erb
  config/environments/test.rb
  config/locales/en.yml
  spec/controllers/sessions_controller_spec.rb
Labels: v2.2

#614 GRN2-175: Update Greenlight to work with the new launcher
  app/helpers/sessions_helper.rb
  config/initializers/omniauth.rb
Labels: v2.2

#617 GRN2-179: Replaced old colour picker with a cleaner one
  app/assets/javascripts/admins.js
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.scss
  app/views/admins/index.html.erb
  app/views/shared/_footer.html.erb
  vendor/assets/images/colourPicker/blank.gif
  vendor/assets/images/colourPicker/colorpicker_background.png
  vendor/assets/images/colourPicker/colorpicker_hex.png
  vendor/assets/images/colourPicker/colorpicker_hsb_b.png
  vendor/assets/images/colourPicker/colorpicker_hsb_h.png
  vendor/assets/images/colourPicker/colorpicker_hsb_s.png
  vendor/assets/images/colourPicker/colorpicker_indic.gif
  vendor/assets/images/colourPicker/colorpicker_overlay.png
  vendor/assets/images/colourPicker/colorpicker_rgb_b.png
  vendor/assets/images/colourPicker/colorpicker_rgb_g.png
  vendor/assets/images/colourPicker/colorpicker_rgb_r.png
  vendor/assets/images/colourPicker/colorpicker_select.gif
  vendor/assets/images/colourPicker/colorpicker_submit.png
  vendor/assets/images/colourPicker/custom_background.png
  vendor/assets/images/colourPicker/custom_hex.png
  vendor/assets/images/colourPicker/custom_hsb_b.png
  vendor/assets/images/colourPicker/custom_hsb_h.png
  vendor/assets/images/colourPicker/custom_hsb_s.png
  vendor/assets/images/colourPicker/custom_indic.gif
  vendor/assets/images/colourPicker/custom_rgb_b.png
  vendor/assets/images/colourPicker/custom_rgb_g.png
  vendor/assets/images/colourPicker/custom_rgb_r.png
  vendor/assets/images/colourPicker/custom_submit.png
  vendor/assets/images/colourPicker/select.png
  vendor/assets/images/colourPicker/select2.png
  vendor/assets/images/colourPicker/slider.png
  vendor/assets/javascripts/colorpicker.js
  vendor/assets/stylesheets/colorpicker.scss
Labels: v2.2

#618 GRN2-168-fix: Fixed issue appearing after creating a room with Admin
  app/helpers/rooms_helper.rb
Labels: v2.2

#619 GRN2-30: Add custom ldap sign in page
  Gemfile
  Gemfile.lock
  app/assets/images/ldap-logo.png
  app/assets/stylesheets/main.scss
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/views/shared/_header.html.erb
  app/views/users/ldap_signin.html.erb
  config/initializers/omniauth.rb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/sessions_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: changes requested, v2.2

#620 GRN2-192: Made error pages more descriptive
  app/controllers/application_controller.rb
  app/controllers/errors_controller.rb
  app/views/errors/bigbluebutton_error.html.erb
  app/views/errors/internal_error.html.erb
  app/views/errors/not_found.html.erb
  app/views/errors/unauthorized.html.erb
  app/views/errors/unprocessable.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/errors_controller_spec.rb
Labels: changes requested, v2.2

#626 GRN2-195: Fixed issues with turbolinks caching
  app/assets/javascripts/main.js
  app/helpers/sessions_helper.rb
  app/views/admins/index.html.erb
  app/views/layouts/application.html.erb
  config/locales/en.yml
Labels: v2.2

#630 GRN2-193: By default, recordings should be sorted descendingly by their date
  app/models/concerns/api_concern.rb
Labels: v2.2.1

#637 GRN2-198: Update sample.env with the correct links
  sample.env
Labels: v2.2.1

#636 GRN2-45, GRN2-197: Upgrade Rails to 5.2.3 and removed sass-rails gem
  Gemfile
  Gemfile.lock
  app/controllers/concerns/themer.rb
  app/controllers/themes_controller.rb
  bin/bundle
  bin/setup
  bin/update
  bin/yarn
  config/application.rb
  config/boot.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/new_framework_defaults.rb
  config/puma.rb
  config/spring.rb
  config/storage.yml
Labels: v2.2.1

#631 GRN2-194: Decrease amount of database calls on the admin panel
  app/controllers/admins_controller.rb
  app/controllers/application_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/helpers/rooms_helper.rb
  app/helpers/sessions_helper.rb
  app/helpers/theming_helper.rb
  app/models/user.rb
  app/views/shared/_header.html.erb
Labels: v2.2.1

#655 GRN2-205: Fixed issue with https redirect
  app/controllers/application_controller.rb
Labels: v2.2.1

#672 Added cache layer to cloudbuild
  cloudbuild-staging.yaml
  cloudbuild.yaml
Labels: v2.2.2

#674 Unify error pages
  app/controllers/application_controller.rb
  app/controllers/errors_controller.rb
  app/views/errors/greenlight_error.html.erb
  app/views/errors/internal_error.html.erb
  app/views/errors/not_found.html.erb
  app/views/errors/unauthorized.html.erb
  config/locales/en.yml
  spec/controllers/admins_controller_spec.rb
  spec/controllers/application_controller_spec.rb
Labels: v2.2.2

#646 GRN2-199: Allow room owners to set a password that is required to join a room
  app/assets/javascripts/room.js.erb
  app/assets/stylesheets/rooms.scss
  app/controllers/rooms_controller.rb
  app/views/rooms/join.html.erb
  app/views/rooms/wait.html.erb
  app/views/shared/_room_event.html.erb
  app/views/shared/components/_room_block.html.erb
  app/views/shared/modals/_create_room_modal.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20190711192033_add_password_digest_to_rooms.rb
  db/schema.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v2.3

#658 Fix the dockerfile for the new version of rails
  Dockerfile
Labels: v2.3

#675 GRN2-211: Added a maintenance mode
  .dockerignore
  Jenkinsfile
  app/controllers/application_controller.rb
  app/controllers/themes_controller.rb
  config/locales/en.yml
Labels: v2.2.2

#634 GRN2-29: Recording visibility by default should be configurable
  app/controllers/admins_controller.rb
  app/controllers/application_controller.rb
  app/helpers/admins_helper.rb
  app/models/room.rb
  app/views/admins/components/_settings.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/admins_controller_spec.rb
Labels: v2.3

#664 GRN2-xx: Don't sent email if there are no admins
  app/controllers/concerns/emailer.rb
Labels: v2.3

#635 GRN2-200: Add settings required for watchtower as part of the settings passed in the room create call
  app/controllers/application_controller.rb
  app/models/room.rb
Labels: v2.3

#679 GR2-213: Added an env variable that allows maitenance mode
  app/controllers/application_controller.rb
  app/models/application_record.rb
  config/locales/en.yml
  sample.env
Labels: v2.2.2

#680 Allowed users to start rooms if database is in readonly
  app/models/room.rb
Labels: v2.2.2

#682 GRN2-213: Cleaned up omniauth user create
  app/models/user.rb
Labels: v2.2.2

#647 GRN2-201: In single tenant, if there is only one login provider, clicking on the sign in button should take you directly to the auth login
  app/controllers/users_controller.rb
Labels: v2.3

#683 GRN2-xx: Fixed issues with maintenance mode
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
  bin/start
Labels: v2.2.2

#648 GRN2-145: Single sign on for super admins
  app/helpers/sessions_helper.rb
  config/initializers/session_store.rb
  spec/controllers/admins_controller_spec.rb
  spec/controllers/themes_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: v2.3

#650 GRN2-202: Create a room in which everyone joins as Moderator (Fixed #628)
  app/assets/javascripts/room.js.erb
  app/controllers/rooms_controller.rb
  app/views/rooms/join.html.erb
  app/views/shared/modals/_create_room_modal.html.erb
  config/locales/en.yml
  sample.env
  spec/controllers/rooms_controller_spec.rb
Labels: v2.3

#651 GRN2-203: Widen the field with the invite url (Fixes: #638)
  app/views/rooms/show.html.erb
Labels: v2.3

#659 GRN2-210: Add ability to search by role
  app/controllers/admins_controller.rb
  app/models/user.rb
  config/locales/en.yml
Labels: v2.3

#663 GRN2-208: Implement missing health checks
  Gemfile
  Gemfile.lock
  config/initializers/health_check.rb
Labels: v2.3

#660 GRN2-209: Add room setting to require moderator approval
  app/assets/javascripts/room.js.erb
  app/controllers/rooms_controller.rb
  app/models/room.rb
  app/views/shared/modals/_create_room_modal.html.erb
  config/locales/en.yml
  sample.env
  spec/controllers/rooms_controller_spec.rb
Labels: v2.3

#687 GRN2-214: Fixed issue with image being replaced on every sign in (Fixed #669)
  app/models/user.rb
Labels: v2.3

#661 GRN2-206: Remove support for the flash client Fixes(#654)
  app/assets/javascripts/room.js.erb
  app/controllers/rooms_controller.rb
  app/models/room.rb
  app/views/shared/modals/_create_room_modal.html.erb
  config/locales/en.yml
  sample.env
  spec/controllers/rooms_controller_spec.rb
  spec/models/room_spec.rb
Labels: v2.3

#656 Add support for roles
  Gemfile
  Gemfile.lock
  app/controllers/sessions_controller.rb
  sample.env
Labels: v2.3

#691 Change env variable name for thes session store
  config/initializers/session_store.rb
Labels: v2.3

#692 GRN2-xx: Updated strings and added a bit of styling
  app/assets/stylesheets/application.scss
  app/views/shared/modals/_create_room_modal.html.erb
  app/views/users/new.html.erb
  config/locales/en.yml
Labels: v2.3

#693 GRN2-xx: Fixed delete user modal in Manage Users
  app/views/admins/components/_users.html.erb
Labels: v2.3

#694 GRN2-xx: Switched to Lograge for logging and increased log level to info
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  config/environments/production.rb
Labels: v2.3

#699 GRN2-xx: Removed readonly maintenance mode
  app/controllers/application_controller.rb
  app/models/application_record.rb
  app/models/room.rb
  app/models/user.rb
  bin/start
  config/locales/en.yml
  sample.env
Labels: v2.2.4

#701 GRN2-xx: General bug fixes and improvements for 2.3
  app/controllers/admins_controller.rb
  app/helpers/admins_helper.rb
  app/views/admins/components/_settings.html.erb
  config/locales/en.yml
  spec/controllers/admins_controller_spec.rb
Labels: v2.3

#696 GRN2-216: Added All Join as Moderator room setting
  app/assets/stylesheets/utilities/_primary_themes.scss
  app/controllers/rooms_controller.rb
  app/views/shared/modals/_create_room_modal.html.erb
  config/locales/en.yml
  sample.env
  spec/controllers/rooms_controller_spec.rb
Labels: v2.3

#711 GRN2-xx: Added back fix for ldap image and fixed issue with ldap redirect (Fixed #712)
  app/controllers/users_controller.rb
  app/models/user.rb
Labels: v2.3

#708 GRN2-218: Create a rake task to create users
  lib/tasks/administrator.rake
  lib/tasks/user.rake
Labels: v2.3

#707 GRN2-217: Fixes issues with recording rows and localization (fixed #703-#705)
  app/controllers/users_controller.rb
  app/helpers/recordings_helper.rb
  app/views/shared/components/_public_recording_row.html.erb
  app/views/shared/components/_recording_row.html.erb
  config/environments/production.rb
  config/locales/en.yml
  spec/controllers/users_controller_spec.rb
  spec/helpers/recordings_helper_spec.rb
Labels: v2.3
