Repository bigbluebutton/greenlight, pull requests merged in 2020-08, with the labels that each got.

#1872 small cosmetic changes
  app/assets/stylesheets/application.scss
  app/helpers/theming_helper.rb
  config/locales/en.yml
Labels: v2.7.1

#1966 GRN2-xx: Allowed file types now matches BigBlueButton
  app/controllers/rooms_controller.rb
  app/views/shared/modals/_preupload_presentation_modal.html.erb
  config/application.rb
  config/locales/en.yml
  spec/controllers/rooms_controller_spec.rb
  spec/fixtures/files/invalid.bmp
  spec/fixtures/files/invalid.jpg
Labels: v2.7.1

#1987 GRN2-xx: Fixed issue causing account verify to throw 404
  app/controllers/account_activations_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/sessions_controller.rb
  spec/controllers/account_activations_controller_spec.rb
  spec/controllers/sessions_controller_spec.rb
Labels: v2.7.1

#1977 Allow uploading larger presentations
  greenlight.nginx
Labels: v2.7.1

#1988 GRN2-xx: Hide recording table when disabled through room config
  app/helpers/application_helper.rb
  app/views/rooms/components/_room_event.html.erb
  app/views/rooms/show.html.erb
  app/views/shared/_header.html.erb
Labels: v2.7.1

#2026 GRN2-xx: Added option to set Action Cable URL
  config/cable.yml
Labels: v2.7.3

#2027 GRN2-xx: Changed room joining post to hopefully fix CSRF errors
  app/assets/javascripts/wait.js
Labels: v2.7.3

#2040 GRN2-xx: Add env variables to change same_site and secure
  config/initializers/session_store.rb
Labels: v2.7.3

#2034 [security] Fix Cross-Site-Scripting Vulnerability
  app/assets/javascripts/room.js
Labels: v2.7.3

#2043 GRN2-xx: More work to fix CSRF issue on join
  app/controllers/rooms_controller.rb
Labels: v2.7.3

#2014 LDAP Sign-In form: user field attributes
  app/views/sessions/ldap_signin.html.erb
Labels: v2.7.2
