Repository bigbluebutton/greenlight, pull requests merged in 2020-03, with the labels that each got.

#978 GRN2-233: Scoped reset password to provider
  app/controllers/password_resets_controller.rb
Labels: v2.5

#979 GR2-xx: Fixed order of rooms in postgres
  app/models/user.rb
Labels: v2.5

#995 GRN2-283: Fixed bug where users can't join a shared room (Fixed #989)
  app/controllers/rooms_controller.rb
Labels: v2.5.1

#1016 GRN2-xx: Added option to specify different redirect url for google auth
  config/initializers/omniauth.rb
  sample.env
Labels: v2.5.1

#1021 Updated documentation urls
  sample.env
Labels: v2.5.1

#996 GRN2-284: Fixed bug where admin rights emails was sent multiple times (Fixed #988)
  app/controllers/concerns/rolify.rb
Labels: v2.5.1

#1029 GRN2-xx: Add callback location for each provider
  config/initializers/omniauth.rb
Labels: v2.5.1

#1027 GRN2-xx: Fixed issue with users not being muted when joining room
  app/controllers/concerns/joiner.rb
Labels: v2.5.1

#1047 GRN2-xx: Fixed bugs in Administrator Panel
  app/models/room.rb
  app/views/admins/components/_server_room_row.html.erb
Labels: v2.5.1

#1048 GRN2-xx: Added log line when BigBlueButton exception occurs
  app/controllers/application_controller.rb
Labels: v2.5.1

#1049 GRN2-xx: Removed placeholder text for maintenance window
  app/controllers/application_controller.rb
  spec/models/room_spec.rb
Labels: v2.5.1

#1019 allow for mail system without authentication
  config/environments/production.rb
Labels: v2.5.1

#1051 GRN2-xx: Fixed issue with adding roles
  app/controllers/concerns/rolify.rb
Labels: v2.5.2
