Repository bigbluebutton/greenlight, pull requests merged in 2020-06, with the labels that each got.

#1721 GR2-xx: Fix rename recordings
  app/assets/javascripts/rename.js
Labels: v2.6.3

#1720 GRN2-xx: Removed default order by priority on roles
  app/controllers/concerns/rolify.rb
  app/helpers/users_helper.rb
  app/models/role.rb
Labels: v2.6.3

#1726 GRN2-xx: Redirect signed in users to their home page
  app/controllers/application_controller.rb
  app/controllers/main_controller.rb
  app/helpers/application_helper.rb
  spec/controllers/main_controller_spec.rb
Labels: v2.6.3

#1728 GRN2-xx: Fixed issue with LDAP role not being respected
  app/controllers/sessions_controller.rb
  app/models/concerns/auth_values.rb
Labels: v2.6.3

#1703 Added optional SMTP_OPENSSL_VERIFY_MODE
  config/environments/production.rb
  sample.env
Labels: v2.6.3

#1736 GRN2-xx: Updated sample env for SMTP setting
  sample.env
Labels: v2.6.3

#1737 GRN2-xx: Fixed Role not exist warning in user create
  lib/tasks/user.rake
Labels: v2.6.3

#1751 GRN2-xx: Fixed user create task failing with invalid role
  lib/tasks/user.rake
Labels: v2.6.4

#1778 GRN2-xx: Fixed issue causing manage users to through 500
  app/controllers/concerns/populator.rb
Labels: v2.6.5

#1779 GRN2-xx: Added ability to map attributes for LDAP
  Gemfile
  Gemfile.lock
  app/controllers/sessions_controller.rb
  sample.env
Labels: v2.6.5

#1784 GRN2-xx: Sanitize search for users and rooms
  app/models/room.rb
  app/models/user.rb
Labels: v2.6.5

#1786 GRN2-xx: Cleaned up manage users query
  app/controllers/admins_controller.rb
  app/controllers/concerns/populator.rb
  app/models/user.rb
Labels: v2.6.5

#1792 GRN2-xx: Fix issue with search in manage users
  app/controllers/concerns/populator.rb
Labels: v2.6.5

#1477 Fix wrong conditional (reported by LGTM)
  app/assets/javascripts/wait.js
Labels: v2.7

#1780 [FIX] Unable to edit long recording names #1776
  app/assets/stylesheets/rooms.scss
Labels: v2.7

#1777 Desgin for Manage Users Tabs
  app/assets/stylesheets/admins.scss
  app/views/admins/components/_manage_users_tags.html.erb
  app/views/shared/components/_subtitle.html.erb
  lib/assets/_primary_themes.scss
Labels: v2.7

#1845 GRN2-xx: Minor style changes to manage users
  app/views/admins/components/_manage_users_tags.html.erb
  lib/assets/_primary_themes.scss
Labels: v2.7

#1775 Maintenance banner moved to admin site
  app/assets/javascripts/admins.js
  app/assets/stylesheets/application.scss
  app/controllers/application_controller.rb
  app/helpers/theming_helper.rb
  app/views/admins/components/_settings.html.erb
  config/locales/en.yml
  spec/controllers/admins_controller_spec.rb
Labels: v2.7

#1296 Make recording of a session optional - Fix #1163
  app/assets/javascripts/room.js
  app/controllers/concerns/joiner.rb
  app/controllers/rooms_controller.rb
  app/models/room.rb
  app/models/setting.rb
  app/views/admins/components/_room_settings.html.erb
  app/views/rooms/components/_room_event.html.erb
  app/views/shared/modals/_create_room_modal.html.erb
  config/application.rb
  config/locales/en.yml
  sample.env
  spec/controllers/rooms_controller_spec.rb
Labels: v2.7

#1601 Enhance Room OpenGraph Metadata
  app/views/layouts/application.html.erb
  app/views/rooms/components/_room_event.html.erb
  app/views/rooms/show.html.erb
Labels: v2.7

#1853 GRN2-xx: Tab title now displays the current page name
  app/helpers/application_helper.rb
  app/views/layouts/application.html.erb
  app/views/rooms/components/_room_event.html.erb
  app/views/rooms/show.html.erb
  app/views/shared/components/_subtitle.html.erb
Labels: v2.7
