Repository bigbluebutton/greenlight, pull requests merged in 2020-12, with the labels that each got.

#2324 Fixed issue with account activation allowing it to be circumvented
  app/controllers/account_activations_controller.rb
  spec/controllers/account_activations_controller_spec.rb
Labels: v2.7.10

#2309 Fix Invite Link Separator
  app/controllers/concerns/joiner.rb
Labels: v2.7.11

#2328 Improce Word Wrapping in Recording Table
  app/assets/stylesheets/rooms.scss
Labels: v2.7.11

#2315 Allow Searching for Rooms
  app/assets/javascripts/room.js
  app/assets/stylesheets/admins.scss
  app/views/rooms/show.html.erb
  config/locales/en.yml
Labels: v2.7.11

#2333 Uppercased Name in Full Name
  config/locales/en.yml
Labels: v2.7.11

#2281 fix: health_check SMTP check when no auth required
  app/controllers/health_check_controller.rb
Labels: v2.7.11

#2343 Fixes to room search
  app/assets/javascripts/room.js
  app/assets/stylesheets/admins.scss
  app/assets/stylesheets/rooms.scss
  app/views/rooms/show.html.erb
Labels: v2.7.11

#2366 Fixed 500 caused by room search
  app/models/user.rb
Labels: v2.7.12

#2367 GRN2-306: Added field to track users last login
  app/controllers/concerns/authenticator.rb
  db/migrate/20201214232153_add_last_login_to_users.rb
  db/schema.rb
  spec/controllers/sessions_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: v2.7.12

#2373 GRN2-307: Added mapping roles through email to site settings
  app/assets/javascripts/admins.js
  app/controllers/account_activations_controller.rb
  app/controllers/concerns/authenticator.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/admins_helper.rb
  app/views/admins/components/_settings.html.erb
  app/views/admins/components/site_settings/_registration.html.erb
  config/locales/en.yml
  spec/controllers/account_activations_controller_spec.rb
  spec/controllers/sessions_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: v2.7.12

#2386 Fix a typo
  README.md
Labels: v2.7.13

#2380 GRN2-310: Share Access now dynamically pulls the list of users from the server
  app/assets/javascripts/admins.js
  app/assets/javascripts/room.js
  app/controllers/admins_controller.rb
  app/controllers/concerns/populator.rb
  app/controllers/rooms_controller.rb
  app/controllers/users_controller.rb
  app/models/ability.rb
  app/models/user.rb
  app/views/shared/modals/_merge_user_modal.html.erb
  app/views/shared/modals/_share_room_modal.html.erb
  config/routes.rb
Labels: v2.7.13

#2389 GRN2-309: Allows admins to edit a non-local users name and email
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/views/users/components/_account.html.erb
  spec/controllers/users_controller_spec.rb
Labels: v2.7.13

#2390 GRN2-314: Make room delete permanent
  app/controllers/rooms_controller.rb
  app/controllers/users_controller.rb
  spec/controllers/users_controller_spec.rb
Labels: v2.7.13

#2397 Only return required info for dynamic user lists
  Gemfile
  Gemfile.lock
  app/controllers/admins_controller.rb
  app/controllers/users_controller.rb
Labels: security, v2.7.14
