Repository bigbluebutton/greenlight, pull requests merged in 2020-05, with the labels that each got.

#1299 GRN2-xx: Switch the relation between users and roles to make queries cleaner and faster
  app/assets/javascripts/user_edit.js
  app/controllers/admins_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/emailer.rb
  app/controllers/concerns/populator.rb
  app/controllers/concerns/rolify.rb
  app/controllers/recordings_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/admins_helper.rb
  app/helpers/users_helper.rb
  app/models/ability.rb
  app/models/concerns/auth_values.rb
  app/models/role.rb
  app/models/user.rb
  app/views/admins/components/_menu_buttons.html.erb
  app/views/admins/components/_roles.html.erb
  app/views/admins/components/_users.html.erb
  app/views/shared/_header.html.erb
  app/views/users/components/_account.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20190314152108_rolify_create_roles.rb
  db/migrate/20200413150518_add_role_id_to_users.rb
  db/schema.rb
  lib/tasks/room.rake
  lib/tasks/user.rake
  spec/controllers/account_activations_controller_spec.rb
  spec/controllers/admins_controller_spec.rb
  spec/controllers/application_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
  spec/controllers/sessions_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories.rb
  spec/models/user_spec.rb
  spec/spec_helper.rb
Labels: v2.6

#1510 Adding translation
  app/views/users/components/_account.html.erb
  config/locales/en.yml
Labels: v2.6

#1488 Fix "for" attribute for label elements
  app/views/admins/components/_roles.html.erb
  app/views/password_resets/edit.html.erb
  app/views/password_resets/new.html.erb
  app/views/sessions/new.html.erb
  app/views/users/components/_account.html.erb
Labels: v2.6

#1478 Fix some issues reported by LGTM
  app/assets/javascripts/admins.js
  app/assets/javascripts/room.js
Labels: v2.6

#1332 Puma Worker Configuration
  config/puma.rb
  sample.env
Labels: v2.6

#1534 GRN2-xx: Name and email for non-local accounts can no longer be updated
  .rubocop.yml
  app/controllers/users_controller.rb
  app/views/users/components/_account.html.erb
  spec/controllers/users_controller_spec.rb
Labels: v2.6

#1532 Fixed hardcoded string
  app/views/main/components/_features.html.erb
Labels: v2.6

#1535 fixed spelling error that was bugging me :) - sep a rat e
  config/locales/en.yml
Labels: v2.6

#1543 GRN2-xx: Added SAFE_HOSTS env variable to block unknown hosts
  app/controllers/application_controller.rb
  app/controllers/concerns/errors.rb
  app/controllers/themes_controller.rb
  sample.env
Labels: v2.5.6

#1545 GRN2-xx: Allow SAFE_HOSTS to be left blank
  app/controllers/application_controller.rb
  config/environments/production.rb
Labels: v2.5.6

#1546 GR2-xx: Updated gems to point to rubygems
  Gemfile
  Gemfile.lock
Labels: v2.5.6

#1549 GRN2-xx: Remove production check for hosts
  app/controllers/application_controller.rb
Labels: v2.5.6

#1550 GRN2-xx: Added port to database configuration
  config/database.yml
  sample.env
Labels: v2.5.6

#1565 Fix rake task user:create so that users can be created when terms are present
  lib/tasks/user.rake
Labels: v2.6

#1451 More secure room ID
  app/models/room.rb
Labels: v2.6

#1421 Legal and privpolicy link
  app/assets/javascripts/admins.js
  app/helpers/theming_helper.rb
  app/models/setting.rb
  app/views/admins/components/_settings.html.erb
  app/views/shared/_footer.html.erb
  config/locales/en.yml
  spec/controllers/admins_controller_spec.rb
Labels: v2.6

#1591 GRN2-295:Refactored update profile and update password
  .rubocop.yml
  app/controllers/users_controller.rb
  app/views/users/components/_password.html.erb
  config/routes.rb
  spec/controllers/users_controller_spec.rb
Labels: v2.6

#1592 GRN2-296: Fixed email sending when not supposed to
  app/controllers/concerns/rolify.rb
Labels: v2.6

#1580 Design changes for small screens
  app/assets/javascripts/room.js
  app/views/admins/components/_recordings.html.erb
  app/views/admins/components/_rooms.html.erb
  app/views/admins/components/_users.html.erb
  app/views/password_resets/edit.html.erb
  app/views/password_resets/new.html.erb
  app/views/rooms/cant_create_rooms.html.erb
  app/views/shared/_sessions.html.erb
  app/views/shared/components/_subtitle.html.erb
  app/views/users/components/_account.html.erb
  lib/assets/_primary_themes.scss
Labels: v2.6

#1560 Make Greenlight work with Ruby 2.7
  Gemfile.lock
Labels: v2.6

#1199 use email input for sign in
  app/views/sessions/new.html.erb
  app/views/sessions/signin.html.erb
  app/views/shared/modals/_invite_user_modal.html.erb
  app/views/users/components/_account.html.erb
Labels: v2.6

#1593 Fix Gemfile
  Gemfile.lock
Labels: v2.6

#1632 GRN2-298: Fixed invalid token for password reset
  app/controllers/password_resets_controller.rb
  config/locales/en.yml
  spec/controllers/password_resets_controller_spec.rb
Labels: v2.6

#1636 GRN2-299: HELP_URL env variable now works as expected
  config/application.rb
Labels: v2.6

#1403 #1372 Fix for long Text in Table + Remove invalid HTML Tag
  app/assets/stylesheets/main.scss
  app/views/admins/components/_recordings.html.erb
  app/views/admins/components/_rooms.html.erb
  app/views/admins/components/_server_recording_row.html.erb
  app/views/admins/components/_server_room_row.html.erb
  app/views/shared/components/_public_recording_row.html.erb
  app/views/shared/components/_recording_row.html.erb
Labels: v2.6

#1644 GRN2-301: Added more validation on profile image
  app/controllers/sessions_controller.rb
  app/helpers/application_helper.rb
  app/views/shared/_header.html.erb
  app/views/users/components/_account.html.erb
  config/routes.rb
  spec/controllers/sessions_controller_spec.rb
Labels: v2.6

#1649 GRN2-300: Changed workflow for users who can't create rooms but have shared rooms
  app/controllers/concerns/authenticator.rb
  app/controllers/concerns/populator.rb
  app/controllers/rooms_controller.rb
  app/helpers/application_helper.rb
  app/views/rooms/show.html.erb
  app/views/shared/_header.html.erb
  config/routes.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v2.6

#1667 Revert "Puma Worker Configuration"
  config/puma.rb
  sample.env
Labels: v2.6

#1668 GRN2-304: Removed html safe from all flash messages
  app/controllers/application_controller.rb
  app/views/errors/bigbluebutton_error.html.erb
  app/views/shared/_flash_messages.html.erb
Labels: v2.6

#1669 GRN2-305: Remove hardcoded guest=true if require mod approval is set
  app/controllers/concerns/bbb_server.rb
Labels: v2.6

#1670 GRN2-302: Change random generation for room uid
  app/models/room.rb
Labels: v2.6

#1671 GRN2-290: Update gems and update to Rails 5.2.4.3
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/sessions_controller.rb
  config/puma.rb
  spec/controllers/password_resets_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories.rb
  spec/rails_helper.rb
Labels: v2.6

#1677 GRN2-xx: Fixes for 2.6
  app/controllers/admins_controller.rb
  app/views/shared/_footer.html.erb
  app/views/shared/modals/_invite_user_modal.html.erb
  config/puma.rb
Labels: v2.6

#1680 GRN2-xx: Fix date for duplicate rooms
  app/helpers/admins_helper.rb
Labels: v2.6

#1690 GRN2-xx: Fixed user create rake task
  lib/tasks/user.rake
Labels: v2.6.2

#1694 GRN2-xx: Home rooms are created for all users with role if can_create_rooms is enabled
  app/controllers/concerns/rolify.rb
  app/models/user.rb
  spec/controllers/admins_controller_spec.rb
Labels: v2.6.2

#1695 GRN2-xx: Fixed room remove task
  lib/tasks/room.rake
Labels: v2.6.2

#1700 GRN2-xx: Upgrade LDAP gem version
  Gemfile
  Gemfile.lock
Labels: v2.6.2
