Repository bigbluebutton/greenlight, pull requests merged in 2020-09, with the labels that each got.

#2046 One more piece for show/hide recording
  app/views/rooms/show.html.erb
Labels: v2.7.3

#2054 GRN2-xx: Fixed bug allowing users to access their own room when they aren't allowed
  app/controllers/rooms_controller.rb
Labels: v2.7.3

#2056 GRN2-xx: Added confirm modal when deleting recording
  app/assets/javascripts/recording.js
  app/views/admins/components/_server_recording_row.html.erb
  app/views/admins/server_recordings.html.erb
  app/views/shared/_sessions.html.erb
  app/views/shared/components/_recording_row.html.erb
  app/views/shared/modals/_delete_recording_modal.html.erb
  config/locales/en.yml
Labels: v2.7.3

#2062 Docker ignore new security policy
  .dockerignore
Labels: v2.7.3

#2089 GRN2-xx: Added back ability to set maintenance window through env variables
  app/controllers/application_controller.rb
  app/views/admins/components/site_settings/_administration.html.erb
Labels: v2.7.4

#2083 fixes #2082 proper link in mail
  app/mailers/user_mailer.rb
  app/views/user_mailer/user_promoted.html.erb
  app/views/user_mailer/user_promoted.text.erb
Labels: v2.7.4

#2092 GRN2-xx: Fixed 404 on room join for users without rooms
  app/controllers/application_controller.rb
  app/controllers/rooms_controller.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v2.7.4

#2095 GRN2-xx: Added back join retry as fallback
  app/assets/javascripts/wait.js
Labels: v2.7.4

#2096 GRN2-xx: Set default cable adapter to postgres
  sample.env
Labels: v2.7.4

#2109 GRN2-xx: Fixed 500 when there is an invalid profile picture
  app/views/rooms/cant_create_rooms.html.erb
Labels: v2.7.5

#2108 GRN2-xx: Fixed 500 caused by editting a user when not allowed to
  app/controllers/users_controller.rb
  spec/controllers/users_controller_spec.rb
Labels: v2.7.5

#2110 GRN2-xx: Fixed 404 when resending verification email
  app/controllers/account_activations_controller.rb
  app/views/account_activations/show.html.erb
Labels: v2.7.5

#2114 Basic anti-spam measures: Add anti-url validation to name
  app/models/user.rb
  spec/models/user_spec.rb
Labels: v2.7.5

#2107 Allow customization of test email recipient
  lib/tasks/configuration.rake
  sample.env
Labels: v2.7.5

#2121 GRN2-xx: ENABLE_SSL is now defaulted to true for new installations
  sample.env
Labels: v2.7.5

#1144 Test email configuration during setup
  lib/tasks/configuration.rake
Labels: v2.7.5

#2139 GRN2-xx: Switched default cable adapter to postgres
  config/cable.yml
Labels: v2.7.6

#1701 Puma Worker Configuration
  config/puma.rb
  sample.env
Labels: v2.7.6

#2140 GRN2-xx: Manually encode the ampersand in a presentation file name
  app/controllers/concerns/bbb_server.rb
Labels: v2.7.6
