Repository bigbluebutton/greenlight, pull requests merged in 2020-04, with the labels that each got.

#1026 GRN2-xx: Updated restart policy for db container
  docker-compose.yml
Labels: v2.5.3

#1090 GRN2-xx: Fixed issue with duplicate roles from LDAP sigin
  app/models/concerns/auth_values.rb
Labels: v2.5.3

#1092 GRN2-xx: Prevented LDAP sign in without password
  app/controllers/sessions_controller.rb
  spec/controllers/sessions_controller_spec.rb
Labels: v2.5.3

#1140 GRN2-xx: Admin actions are now dictated by the correct role permission
  app/assets/javascripts/room.js
  app/controllers/admins_controller.rb
  app/controllers/concerns/joiner.rb
  app/controllers/rooms_controller.rb
  app/controllers/users_controller.rb
  app/models/ability.rb
  app/models/user.rb
  spec/controllers/admins_controller_spec.rb
  spec/models/user_spec.rb
Labels: v2.5.3

#1152 GRN2-xx: Remove hardcoded role value
  app/models/concerns/auth_values.rb
Labels: v2.5.3

#1149 GRN2-xx: Added fallback message if image url is invalid
  app/views/shared/_header.html.erb
  config/locales/en.yml
Labels: v2.5.3

#1155 GRN2-xx: Fixed configuration rake task check
  lib/tasks/configuration.rake
Labels: v2.5.3

#1202 fix cookie banner height
  app/assets/stylesheets/application.scss
Labels: v2.5.4

#1161 make help link configurable
  app/views/shared/_header.html.erb
  config/application.rb
  sample.env
Labels: v2.5.4

#1203 room block enhancements
  app/assets/javascripts/room.js
  app/assets/stylesheets/rooms.scss
  app/views/admins/components/_server_room_row.html.erb
  app/views/rooms/components/_room_block.html.erb
  app/views/rooms/components/_shared_room_block.html.erb
  app/views/rooms/show.html.erb
  app/views/shared/modals/_create_room_modal.html.erb
  lib/assets/_primary_themes.scss
Labels: v2.5.4

#1254 GRN2-xx: Fixed server recordings 500 if user doesn't have an email
  app/controllers/concerns/recorder.rb
  app/helpers/admins_helper.rb
Labels: v2.5.4

#1257 GRN2-xx: Remove report issue from being included automatically
  sample.env
Labels: v2.5.4

#1252 GRN2-xx: Add check to make sure ldap username isn't blank
  app/controllers/sessions_controller.rb
  spec/controllers/sessions_controller_spec.rb
Labels: v2.5.4

#1302 Color Configuration for Cookie Banner
  app/assets/stylesheets/application.scss
  app/views/shared/components/_cookie_warning.html.erb
Labels: v2.5.4

#1308 GRN2-xx: Fixed role permission check for update_recording and delete_recording
  app/controllers/recordings_controller.rb
Labels: v2.5.4

#1318 GRN2-xx: Updated ldap gem to newest version
  Gemfile
  Gemfile.lock
Labels: v2.5.4

#1287 Additional LDAP Authentication Methods
  app/controllers/sessions_controller.rb
  config/initializers/omniauth.rb
  sample.env
Labels: v2.5.4

#1250 GRN2-xx: Replaced bbb_id field with a better string generator
  app/models/room.rb
Labels: v2.5.4

#1319 GRN2-xx: Local account email is now downcased to match the downcased value stored in db
  app/controllers/sessions_controller.rb
Labels: v2.5.4

#1306 Allow to set a filter for LDAP authentication
  app/controllers/sessions_controller.rb
  sample.env
Labels: v2.5.4

#1364 GRN2-xx: Store a random user id for unauthenticated users as a cookie
  app/controllers/concerns/joiner.rb
  spec/controllers/rooms_controller_spec.rb
Labels: on hold

#1378 GRN2-xx: Fixed translation location for room status
  app/views/admins/components/_server_room_row.html.erb
  config/locales/en.yml
Labels: v2.5.5

#1222 GRN2-xx: Added room configuration tab to allow admins to set room settings as always enabled, optional or disabled
  app/assets/javascripts/room.js
  app/assets/stylesheets/rooms.scss
  app/controllers/admins_controller.rb
  app/controllers/concerns/joiner.rb
  app/controllers/rooms_controller.rb
  app/helpers/admins_helper.rb
  app/helpers/rooms_helper.rb
  app/models/ability.rb
  app/models/setting.rb
  app/views/admins/components/_menu_buttons.html.erb
  app/views/admins/components/_room_settings.html.erb
  app/views/admins/room_configuration.html.erb
  app/views/shared/modals/_create_room_modal.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v2.5.5

#1443 GRN2-xx: Bumped LDAP gem version
  Gemfile
  Gemfile.lock
  config/locales/en.yml
Labels: v2.5.5

#1444 GRN2-xx: Restructured email verification and password reset
  app/controllers/account_activations_controller.rb
  app/controllers/admins_controller.rb
  app/controllers/concerns/emailer.rb
  app/controllers/password_resets_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  spec/controllers/account_activations_controller_spec.rb
  spec/controllers/password_resets_controller_spec.rb
  spec/models/user_spec.rb
Labels: v2.5.5
