Repository bigbluebutton/greenlight, pull requests merged in 2020-10, with the labels that each got.

#2147 GRN2-xx: Added env variable to set the default language
  app/controllers/application_controller.rb
  config/application.rb
  sample.env
Labels: v2.7.6

#2151 GRN2-xx: Added timestamp to production logs
  config/environments/production.rb
Labels: v2.7.6

#2152 GRN2-xx: Improvements to create room modal
  app/assets/stylesheets/rooms.scss
  app/views/shared/modals/_create_room_modal.html.erb
Labels: v2.7.6

#2153 GRN2-xx: Removed unused option in code
  app/controllers/concerns/joiner.rb
Labels: v2.7.6

#2161 GRN2-xx: Added a copy access code button
  app/assets/javascripts/room.js
  app/views/rooms/show.html.erb
  config/locales/en.yml
  lib/assets/_primary_themes.scss
Labels: v2.7.6

#2162 GRN2-xx: Added a tab that displays invited users when using Join by Invitation
  app/controllers/admins_controller.rb
  app/controllers/concerns/populator.rb
  app/models/invitation.rb
  app/views/admins/components/_invited_users_table.html.erb
  app/views/admins/components/_manage_users_table.html.erb
  app/views/admins/components/_manage_users_tags.html.erb
  app/views/admins/components/_users.html.erb
  config/locales/en.yml
Labels: v2.7.6

#2169 GRN2-xx: Removed public from public room recordings
  app/views/shared/_sessions.html.erb
Labels: v2.7.6

#2171 GRN2-xx: Updated language dropdown to look nicer
  app/assets/javascripts/user_edit.js
  app/views/users/components/_account.html.erb
Labels: v2.7.6

#2185 GRN2-xx: Bumped Rails to 5.2.4.4
  Gemfile
  Gemfile.lock
Labels: v2.7.6

#2187 allow single quote inside email field
  app/models/user.rb
Labels: v2.7.6

#2214 GRN2-xx: Fixed XSS vulnerability in merge user modal
  app/assets/javascripts/admins.js
Labels: security, v2.7.7

#2215 Fix broken UI on long filenames
  app/assets/stylesheets/rooms.scss
Labels: v2.7.7

#2220 GRN2-xx: Added limit for join name
  app/views/rooms/join.html.erb
Labels: v2.7.7

#2221 GRN2-xx: Hide signin when error occures
  app/controllers/application_controller.rb
  app/helpers/application_helper.rb
  app/views/shared/_header.html.erb
Labels: v2.7.7

#2231 GRN2-xx: Fixed issue with ldap redirect throwing 404
  app/controllers/concerns/authenticator.rb
Labels: v2.7.7

#2232 GRN2-xx: Added a flash message if the getMeetings call times out
  app/controllers/admins_controller.rb
  config/locales/en.yml
Labels: v2.7.7

#2234 Added missing question mark
  app/controllers/admins_controller.rb
  app/controllers/application_controller.rb
  config/locales/en.yml
Labels: v2.7.7

#2245 GRN2-xx: Made rescue clause more specific to catch timeouts for Server Rooms
  app/controllers/admins_controller.rb
Labels: v2.7.8
