Repository bigbluebutton/greenlight, pull requests merged in 2021-01, with the labels that each got.

#2401 GRN2-316: Only pass muteOnStart if set to true
  app/controllers/concerns/bbb_server.rb
Labels: v2.7.15

#2402 GRN2-315: Make all LIKE queries case insensitive
  app/models/concerns/queries.rb
  app/models/room.rb
  app/models/user.rb
Labels: v2.7.15

#1399 Refine OpenID Connect Authentication from #1194
  Gemfile
  Gemfile.lock
  README.md
  app/assets/images/openid-logo.png
  app/assets/stylesheets/main.scss
  app/helpers/application_helper.rb
  config/initializers/omniauth.rb
  config/locales/de_DE.yml
  config/locales/en.yml
  lib/omniauth_options.rb
  sample.env
Labels: In review

#2411 GRN2-277: Optimize server recordings to make it useable for large deployments
  app/assets/stylesheets/admins.scss
  app/controllers/admins_controller.rb
  app/controllers/concerns/populator.rb
  app/controllers/concerns/recorder.rb
  app/models/room.rb
  app/views/admins/components/_manage_users_table.html.erb
  app/views/admins/components/_recordings.html.erb
  app/views/admins/components/_server_room_row.html.erb
  app/views/admins/components/_setting_view.html.erb
  app/views/admins/server_recordings.html.erb
  app/views/shared/components/_subtitle.html.erb
  config/locales/en.yml
  spec/controllers/admins_controller_spec.rb
Labels: v2.7.16

#2431 Removed duplicate code for openid_connect provider
  config/initializers/omniauth.rb
Labels: v2.7.17

#2438 GRN2-258: Times are now rendered using the browsers time zone
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/helpers/admins_helper.rb
  app/helpers/application_helper.rb
  app/helpers/recordings_helper.rb
  app/views/admins/components/_invited_users_table.html.erb
  app/views/admins/components/_manage_users_table.html.erb
  app/views/admins/components/_server_recording_row.html.erb
  app/views/admins/components/_server_room_row.html.erb
  app/views/rooms/components/_room_block.html.erb
  app/views/shared/components/_public_recording_row.html.erb
  app/views/shared/components/_recording_row.html.erb
  spec/helpers/recordings_helper_spec.rb
Labels: v2.7.17

#2442 GRN2-330: Allowed admins to share room with themselves
  app/assets/javascripts/room.js
  app/controllers/users_controller.rb
  app/views/admins/components/_server_room_row.html.erb
  app/views/rooms/components/_room_block.html.erb
  app/views/shared/modals/_share_room_modal.html.erb
Labels: v2.7.17

#2448 GRN2-332: Fixed 500 with share room and merge user
  app/controllers/admins_controller.rb
  app/controllers/users_controller.rb
Labels: v2.7.17

#2449 GRN2-xx: Shortened date for last session to make room block smaller
  app/helpers/application_helper.rb
Labels: v2.7.17

#2470 GRN2-339: Include shared rooms in room count for search
  app/helpers/rooms_helper.rb
  app/views/rooms/show.html.erb
Labels: v2.7.18

#2475 GRN2-340: Added reCAPTCHA to reset password if enabled
  app/controllers/password_resets_controller.rb
  app/views/password_resets/new.html.erb
  config/locales/en.yml
  spec/controllers/password_resets_controller_spec.rb
Labels: v2.7.18
