Repository bigbluebutton/greenlight, pull requests merged in 2021-02, with the labels that each got.

#2512 GRN2-347: Shortened list of users being returned
  app/controllers/rooms_controller.rb
Labels: v2.7.19

#2515 GRN2-xx: Potential fix to unverified users causing 500 error
  app/controllers/concerns/authenticator.rb
Labels: v2.7.19

#2462 fix(omniauth): Correct too many redrect error with OpenID provider
  app/controllers/concerns/authenticator.rb
Labels: v2.7.19

#2523 GRN2-xx: Removed unused button
  app/views/admins/components/site_settings/_settings.html.erb
Labels: v2.7.19

#2528 GRN2-xx: Added sqlite to Gemfile
  Gemfile
  scripts/image_build.sh
Labels: v2.7.20

#2530 GRN2-xx: Only build image on release
  .github/workflows/build.release.yml
Labels: v2.7.20

#2292 Update to Ruby 2.7
  .ruby-version
  Dockerfile
Labels: v2.8

#2553 GRN2-355: Complete refactor of Gemfile and upgraded gems
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/account_activations_controller.rb
  app/controllers/admins_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/authenticator.rb
  app/controllers/concerns/rolify.rb
  app/controllers/health_check_controller.rb
  app/controllers/rooms_controller.rb
  app/controllers/sessions_controller.rb
  app/helpers/application_helper.rb
  app/helpers/users_helper.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  config/application.rb
  config/environments/production.rb
  config/puma.rb
  db/migrate/20190726153012_add_custom_roles.rb
  lib/bbb_api.rb
  lib/omniauth_options.rb
  lib/tasks/migrate_old_office365_users.rake
  lib/tasks/room.rake
  lib/tasks/user.rake
  spec/controllers/rooms_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/spec_helper.rb
  test/mailers/previews/user_mailer_preview.rb
  test/test_helper.rb
Labels: v2.8

#2552 Set timeout for valid_url
  app/helpers/application_helper.rb
Labels: v2.8

#1840 More Resilient Parsing of Booleans
  config/application.rb
Labels: v2.8
