Repository bigbluebutton/greenlight, pull requests merged in 2021-06, with the labels that each got.

#2709 fix URI.escape obsolete warning
  app/views/shared/_flash_messages.html.erb
Labels: v2.8.6

#1589 Added variable in .env to enforce certain domains in account registra…
  app/models/user.rb
  config/application.rb
  config/locales/en.yml
  sample.env
Labels: v2.8.6

#2746 Added failed login logging
  app/controllers/sessions_controller.rb
  app/models/user.rb
Labels: v2.8.6

#2747 Fix LDAP password string
  app/controllers/sessions_controller.rb
  config/locales/en.yml
  spec/controllers/sessions_controller_spec.rb
Labels: v2.8.6

#2750 GRN2-380: Added inaccessible recording format
  app/controllers/concerns/bbb_server.rb
  app/controllers/recordings_controller.rb
  app/views/admins/components/_server_recording_row.html.erb
  app/views/shared/components/_recording_row.html.erb
  config/locales/en.yml
  spec/concerns/bbb_server_spec.rb
Labels: v2.8.6

#2755 Fixed issues with inaccessible recording
  app/views/admins/components/_server_recording_row.html.erb
  app/views/shared/components/_recording_row.html.erb
Labels: v2.8.6

#2756 Upgraded i18n mapping gem
  Gemfile
  Gemfile.lock
  app/helpers/users_helper.rb
Labels: v2.8.6

#2685 Internationalize date format
  app/helpers/application_helper.rb
  config/locales/en.yml
Labels: v2.8.7

#2703 Add autofocus and required attributes
  app/views/sessions/ldap_signin.html.erb
  app/views/sessions/new.html.erb
  app/views/sessions/signin.html.erb
Labels: v2.8.7

#2774 GRN2-381: Moderator access code now being shown in the admin room settings
  app/views/admins/components/_server_room_row.html.erb
Labels: v2.8.7

#2749 fix current user being nil on delete account page
  app/controllers/users_controller.rb
Labels: v2.8.7

#2782 GRN2-383: Fixed overflowing menu
  app/assets/stylesheets/admins.scss
  app/views/admins/components/_rooms.html.erb
Labels: v2.8.8

#2788 GRN2-386: Remove recording sort
  app/views/admins/components/_recordings.html.erb
Labels: v2.8.8

#2720 S3-compatible object storage API
  config/environments/production.rb
  config/storage.yml
  sample.env
Labels: v2.8.8

#2789 GRN2-387: Fixed public recording strings
  app/views/shared/_sessions.html.erb
  config/locales/en.yml
Labels: v2.8.8

#2775 Feat: recording perm
  app/controllers/admins_controller.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/recorder.rb
  app/controllers/concerns/rolify.rb
  app/controllers/rooms_controller.rb
  app/models/role.rb
  app/views/admins/components/_roles.html.erb
  app/views/shared/modals/_create_room_modal.html.erb
  config/locales/en.yml
  config/locales/fr.yml
  db/migrate/20210319160827_add_can_launch_recording_to_permissions.rb
Labels: In review

#2773 remove un-used route
  config/routes.rb
Labels: v2.8.8

#2812 GRN2-385: Recording permission tied to role cleanup
  app/controllers/admins_controller.rb
  app/controllers/concerns/recorder.rb
  app/controllers/rooms_controller.rb
  app/helpers/application_helper.rb
  config/locales/en.yml
  db/schema.rb
Labels: v2.8.8

#2813 GRN2-388: Prevent double hyphens in room names
  app/helpers/application_helper.rb
  app/models/user.rb
Labels: v2.8.8

#2815 Stop disabled settings from being accessible by tab
  app/views/shared/modals/_create_room_modal.html.erb
Labels: v2.8.8

#2819 [fix] avoid printing %{inject} when no_recordings are available
  app/views/shared/_sessions.html.erb
Labels: v2.8.8
