Repository bigbluebutton/greenlight, pull requests merged in 2021-03, with the labels that each got.

#2555 Add open_timeout
  app/helpers/application_helper.rb
Labels: v2.8

#2563 GRN2-354: Switch default database to Postgres 13.2
  .github/workflows/main.yml
  docker-compose.yml
Labels: v2.8

#2565 GRN2-357: Forked the workflows to avoid potential disruption
  .github/workflows/build.push.yml
Labels: v2.8

#2572 GRN2-xx: Replace all CRLF files to LF
  .github/workflows/build.release.yml
  app/views/rooms/show.html.erb
  app/views/shared/modals/_invite_user_modal.html.erb
  app/views/shared/modals/_share_room_modal.html.erb
  app/views/user_mailer/invite_email.html.erb
  app/views/user_mailer/invite_email.text.erb
Labels: v2.8.1

#2413 Add optional moderator codes
  app/assets/javascripts/room.js
  app/assets/stylesheets/rooms.scss
  app/controllers/application_controller.rb
  app/controllers/concerns/joiner.rb
  app/controllers/rooms_controller.rb
  app/helpers/admins_helper.rb
  app/models/setting.rb
  app/views/admins/components/site_settings/_settings.html.erb
  app/views/rooms/components/_enter_access_code_form.html.erb
  app/views/rooms/components/_room_block.html.erb
  app/views/rooms/join.html.erb
  app/views/rooms/show.html.erb
  app/views/shared/modals/_create_room_modal.html.erb
  config/application.rb
  config/locales/de_DE.yml
  config/locales/en.yml
  db/migrate/20210108032132_add_moderator_access_code_to_rooms.rb
  db/schema.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v2.8.1

#2579 GRN2-362: Moved moderator access setting to Room Configuration
  app/controllers/application_controller.rb
  app/views/admins/components/_room_settings.html.erb
  app/views/admins/components/site_settings/_settings.html.erb
  config/application.rb
  config/locales/de_DE.yml
  config/locales/en.yml
  spec/controllers/rooms_controller_spec.rb
Labels: v2.8.1

#2582 GRN2-xx: Small improvements to moderator access code
  app/models/setting.rb
  config/locales/en.yml
Labels: v2.8.1

#2599 GRN2-367: Added valid until text to invite email
  app/controllers/admins_controller.rb
  app/controllers/concerns/emailer.rb
  app/controllers/sessions_controller.rb
  app/mailers/user_mailer.rb
  app/views/user_mailer/invite_email.html.erb
  config/locales/en.yml
  test/mailers/previews/user_mailer_preview.rb
Labels: v2.8.2

#2600 GRN2-368: Fixed 500 if user has no rooms in Latest Recordings
  app/controllers/concerns/populator.rb
Labels: v2.8.2

#2601 GRN2-370: Fixed bug that caused public recordings not to show
  app/views/rooms/join.html.erb
Labels: v2.8.2

#2602 GRN2-369: Add IP Address to logs
  config/environments/production.rb
Labels: v2.8.2

#2609 GRN2-xx: Another fix for unverified accounts
  app/controllers/sessions_controller.rb
Labels: v2.8.2
