Repository bigbluebutton/greenlight, pull requests merged in 2021-09, with the labels that each got.

#2896 GRN2-xx: Fixed issue causing recordings not to show on All Recordings if the user has too many rooms
  app/controllers/concerns/populator.rb
  app/controllers/concerns/recorder.rb
Labels: v2.9.2

#2860 Use the user image for BBB avatar #2 (Limit image size)
  app/controllers/concerns/bbb_server.rb
  app/controllers/concerns/joiner.rb
  app/controllers/rooms_controller.rb
  config/application.rb
  sample.env
Labels: changes requested

#2906 GR2-xx: Social uid rake task
  lib/tasks/user.rake
Labels: v2.10.0

#2907 GRN2-382: Added support for protected recordings
  app/controllers/concerns/bbb_server.rb
  app/controllers/recordings_controller.rb
  app/helpers/application_helper.rb
  app/views/shared/components/_recording_row.html.erb
Labels: v2.10.0

#2916 Avatar URL check - controlling response code
  app/controllers/concerns/joiner.rb
Labels: v2.10.0

#2783 Accessibility fix generate access code
  app/assets/javascripts/room.js
  app/views/shared/modals/_create_room_modal.html.erb
  config/locales/en.yml
Labels: changes requested
