Repository bigbluebutton/greenlight, pull requests merged in 2021-07, with the labels that each got.

#2817 Show access code in welcome message
  app/controllers/concerns/joiner.rb
  spec/concerns/joiner_spec.rb
Labels: v2.8.8

#2834 Allow users to record by default
  app/models/role.rb
Labels: v2.9.0

#2836 Open graph displaying incorrect language bug
  app/controllers/application_controller.rb
  app/views/layouts/application.html.erb
Labels: v2.9.1

#2853 Fix 500 when language is arabic
  config/locales/ar.yml
Labels: v2.9.1
