Repository bigbluebutton/greenlight, pull requests merged in 2022-03, with the labels that each got.

#3266 Setup Frontend connection using Typescript and React #3213
  .gitignore
  .idea/greenlight.iml
  .idea/misc.xml
  app/controllers/components_controller.rb
  app/javascript/application.js
  app/javascript/application.jsx
  app/javascript/components/App.tsx
  app/javascript/components/OtherTest.tsx
  app/javascript/components/Test.tsx
  app/javascript/controllers/application.js
  app/javascript/controllers/hello_controller.js
  app/javascript/controllers/index.js
  app/javascript/routes/Index.jsx
  app/views/components/index.html.erb
  config/initializers/assets.rb
  config/routes.rb
  package-lock.json
  package.json
  yarn.lock
Labels: v3

#3269 Setup Postgres database connection #3216
  .gitignore
  Gemfile
  Gemfile.lock
  config/database.yml
  sample.env
Labels: v3

#3278 Configure Eslint and Jest to work with the frameworks #3215
  .eslintrc.yml
  package-lock.json
  package.json
  yarn.lock
Labels: v3

#3279 Preventing XSS Share Room Access
  app/assets/javascripts/room.js
Labels: security

#3284 Added bootstrap
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/assets/config/manifest.js
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/application.css
  app/javascript/components/Test.tsx
  config/initializers/assets.rb
  package-lock.json
  package.json
  yarn.lock
Labels: v3

#3286 Fixed database names
  config/database.yml
Labels: v3

#3288 Add missing React librairies
  package.json
  yarn.lock
Labels: v3

#3290 Added .ruby-version
  .ruby-version
Labels: v3

#3291 Fixed db names again
  config/database.yml
  config/initializers/assets.rb
Labels: v3

#3292 Created the base User Model
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/models/user.rb
  db/migrate/20220314184634_create_users.rb
  db/schema.rb
  spec/factories/user_factory.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
  spec/support/shoulda_matchers.rb
  test/application_system_test_case.rb
  test/channels/application_cable/connection_test.rb
  test/controllers/.keep
  test/fixtures/files/.keep
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/system/.keep
  test/test_helper.rb
Labels: v3

#3297 Create Room Model #3180
  .rubocop.yml
  app/models/room.rb
  app/models/user.rb
  db/migrate/20220315151617_create_rooms.rb
  db/schema.rb
  spec/factories/room_factory.rb
  spec/models/room_spec.rb
  spec/models/user_spec.rb
Labels: v3

#3310 GLv3-3202-frontend-structure
  app/javascript/app.tsx
  app/javascript/application.jsx
  app/javascript/components/App.tsx
  app/javascript/components/OtherTest.tsx
  app/javascript/components/Test.tsx
  app/javascript/components/stylings/buttons/ButtonLink.jsx
  app/javascript/main.jsx
  app/javascript/routes/Index.jsx
  app/views/components/index.html.erb
  app/views/layouts/application.html.erb
Labels: v3

#3311 GLv3-3202-frontend-form
  app/javascript/app.jsx
  app/javascript/components/forms/Form.jsx
  app/javascript/components/forms/FormControl.jsx
  app/javascript/components/forms/SignupForm.jsx
  app/javascript/components/stylings/Spinner.jsx
  app/javascript/helpers/forms/SignupFormHelpers.jsx
  app/javascript/main.jsx
  app/javascript/routes/Signup.jsx
  package-lock.json
  yarn.lock
Labels: v3

#3317 React bootstrap icons install
  package-lock.json
  package.json
  yarn.lock
Labels: v3

#3322 Added new show action to rooms controller
  .rubocop.yml
  app/controllers/api/v1/rooms_controller.rb
  app/models/room.rb
  config/routes.rb
  db/migrate/20220317142349_create_recordings.rb
  spec/requests/rooms_controller_spec.rb
  spec/services/big_blue_button_api_spec.rb
Labels: v3

#3308 GIT-3306: Fixing the bad date format in Arabic local files.
  config/locales/ar.yml
  config/locales/ar_IQ.yml
Labels: bug, v2

#3327 Add Sign In
  app/controllers/api/v1/sessions_controller.rb
  app/controllers/application_controller.rb
  app/javascript/app.jsx
  app/javascript/components/Home.tsx
  app/javascript/components/sessions/AuthContext.tsx
  app/javascript/components/sessions/SignIn.tsx
  app/javascript/components/user/CurrentUser.tsx
  app/javascript/helpers/forms/SignupFormHelpers.jsx
  app/javascript/main.jsx
  config/routes.rb
Labels: v3

#3319 raise join_name length to 99
  app/views/rooms/join.html.erb
Labels: bug, v2

#3323 Added the frontend components for Show Room
  app/javascript/components/rooms/FeatureTabs.tsx
  app/javascript/components/rooms/Presentation.tsx
  app/javascript/components/rooms/RecordingsTable.tsx
  app/javascript/components/rooms/RoomSettings.tsx
  app/javascript/components/rooms/RoomView.tsx
  app/javascript/components/rooms/SharedAccess.tsx
  app/javascript/main.jsx
  app/views/components/index.html.erb
Labels: v3

#3325 View rooms: Back-end changes
  app/controllers/api/v1/rooms_controller.rb
  config/routes.rb
  spec/controllers/rooms_controller_spec.rb
  spec/requests/rooms_controller_spec.rb
Labels: v3

#3326 View room front end
  app/assets/stylesheets/application.bootstrap.scss
  app/controllers/api/v1/rooms_controller.rb
  app/javascript/components/RoomCard.jsx
  app/javascript/main.jsx
  app/javascript/routes/Rooms.jsx
  config/routes.rb
  spec/requests/rooms_controller_spec.rb
Labels: v3

#3329 Removing rspec rooms controller
  spec/requests/rooms_controller_spec.rb
Labels: v3

#3331 Fixing hovering stlying on rooms card
  app/assets/stylesheets/application.bootstrap.scss
  app/javascript/components/RoomCard.jsx
Labels: v3

#3337 Separated the `getRoom` query into a separate file
  app/javascript/components/rooms/RoomView.jsx
  app/javascript/hooks/queries/rooms/GetRoomQuery.jsx
Labels: v3
