Repository bigbluebutton/greenlight, pull requests merged in 2022-04, with the labels that each got.

#3346 Adding the start session feature.
  .rubocop.yml
  app/assets/stylesheets/application.bootstrap.scss
  app/controllers/api/v1/rooms_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/application_controller.rb
  app/javascript/components/RoomCard.jsx
  app/javascript/components/rooms/RoomView.jsx
  app/javascript/helpers/Axios.jsx
  app/javascript/hooks/mutations/rooms/StartSession.jsx
  app/services/big_blue_button_api.rb
  config/application.rb
  config/routes.rb
Labels: v3

#3347 Styling Sign In Form
  app/assets/stylesheets/application.bootstrap.scss
  app/javascript/components/sessions/SignIn.jsx
Labels: v3

#3357 First stages of refactor
  app/javascript/components/Home.jsx
  app/javascript/components/forms/SignupForm.jsx
  app/javascript/components/rooms/Room.jsx
  app/javascript/components/rooms/RoomCard.jsx
  app/javascript/components/rooms/Rooms.jsx
  app/javascript/components/sessions/AuthContext.jsx
  app/javascript/components/sessions/SignIn.jsx
  app/javascript/components/user/CurrentUser.jsx
  app/javascript/components/users/Signup.jsx
  app/javascript/helpers/Axios.jsx
  app/javascript/hooks/mutations/sessions/useCreateSession.jsx
  app/javascript/hooks/mutations/users/Signup.jsx
  app/javascript/hooks/mutations/users/useCreateUser.jsx
  app/javascript/hooks/queries/rooms/useRoom.jsx
  app/javascript/hooks/queries/rooms/useRooms.jsx
  app/javascript/hooks/queries/rooms/useSessions.jsx
  app/javascript/main.jsx
Labels: v3

#3359 Ran rubocop
  app/controllers/api/v1/rooms_controller.rb
  config/routes.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3358 Ran eslint for the first time
  .eslintrc.yml
  app/javascript/App.jsx
  app/javascript/components/forms/Form.jsx
  app/javascript/components/forms/FormControl.jsx
  app/javascript/components/forms/SignupForm.jsx
  app/javascript/components/rooms/FeatureTabs.jsx
  app/javascript/components/rooms/Presentation.jsx
  app/javascript/components/rooms/RecordingsTable.jsx
  app/javascript/components/rooms/Room.jsx
  app/javascript/components/rooms/RoomCard.jsx
  app/javascript/components/rooms/RoomSettings.jsx
  app/javascript/components/rooms/Rooms.jsx
  app/javascript/components/rooms/SharedAccess.jsx
  app/javascript/components/sessions/AuthContext.jsx
  app/javascript/components/sessions/SignIn.jsx
  app/javascript/components/stylings/Spinner.jsx
  app/javascript/components/stylings/buttons/ButtonLink.jsx
  app/javascript/components/user/CurrentUser.jsx
  app/javascript/components/users/Signup.jsx
  app/javascript/helpers/Axios.jsx
  app/javascript/helpers/forms/SignupFormHelpers.jsx
  app/javascript/hooks/mutations/sessions/useCreateSession.jsx
  app/javascript/hooks/mutations/users/useCreateUser.jsx
  app/javascript/hooks/queries/rooms/useRoom.jsx
  app/javascript/hooks/queries/rooms/useRooms.jsx
  app/javascript/hooks/queries/rooms/useSessions.jsx
  app/javascript/main.jsx
  package-lock.json
  package.json
  yarn.lock
Labels: v3

#3362 Fixed react router issue
  app/javascript/components/rooms/RoomCard.jsx
  app/javascript/components/stylings/buttons/ButtonLink.jsx
  app/javascript/hooks/mutations/sessions/useCreateSession.jsx
  package-lock.json
  package.json
  yarn.lock
Labels: v3

#3360 Github actions changes
  .github/workflows/ci.yml
Labels: v3

#3361 Rooms front end refactor
  app/assets/stylesheets/application.bootstrap.scss
  app/javascript/components/rooms/RoomCard.jsx
  app/javascript/components/rooms/Rooms.jsx
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/components/rooms/RoomsTabs.jsx
Labels: v3

#3367 More refactoring to try and get eslint to pass
  .eslintrc.yml
  .github/workflows/ci.yml
  app/javascript/components/forms/Form.jsx
  app/javascript/components/forms/FormControl.jsx
  app/javascript/components/forms/SignupForm.jsx
  app/javascript/components/rooms/RoomCard.jsx
  app/javascript/components/rooms/Rooms.jsx
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/components/rooms/RoomsTabs.jsx
  app/javascript/components/sessions/AuthProvider.jsx
  app/javascript/components/sessions/SignIn.jsx
  app/javascript/components/stylings/Spinner.jsx
  app/javascript/components/stylings/buttons/ButtonLink.jsx
  app/javascript/components/user/CurrentUser.jsx
  app/javascript/main.jsx
  jest.config.js
  package-lock.json
  package.json
  yarn.lock
Labels: v3

#3368 Refactor Sign In form
  app/javascript/components/sessions/SignIn.jsx
  app/javascript/hooks/mutations/sessions/useCreateSession.jsx
Labels: v3

#3369 Fix Sign In redirect
  app/javascript/hooks/mutations/sessions/useCreateSession.jsx
Labels: v3

#3377 Fixed issue with ButtonLink props
  app/javascript/components/stylings/buttons/ButtonLink.jsx
Labels: v3

#3350 Add Header
  app/javascript/App.jsx
  app/javascript/components/shared/Header.jsx
  app/javascript/components/user/CurrentUser.jsx
Labels: v3

#3378 Adding update option in jest command
  .github/workflows/ci.yml
Labels: v3

#3372 Rework Stylesheets tree
  app/assets/stylesheets/_custom-variables.scss
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/helpers.scss
  app/assets/stylesheets/rooms.scss
Labels: v3

#3382 Adapting #render_json one liner method.
  app/controllers/api/v1/rooms_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/application_controller.rb
Labels: v3

#3355 Backend: Added the room session start feature.
  .rubocop.yml
  app/controllers/api/v1/rooms_controller.rb
  app/services/big_blue_button_api.rb
  config/routes.rb
  spec/controllers/rooms_controller_spec.rb
  spec/services/big_blue_button_api_spec.rb
Labels: v3

#3383 Allow user to share room using URL
  app/javascript/components/rooms/Room.jsx
Labels: v3

#3391 Frontend: Minor restructuring.
  app/javascript/components/Home.jsx
  app/javascript/components/forms/SigninForm.jsx
  app/javascript/components/forms/SignupForm.jsx
  app/javascript/components/rooms/Room.jsx
  app/javascript/components/rooms/RoomCard.jsx
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/components/shared/Header.jsx
  app/javascript/components/shared/stylings/Spinner.jsx
  app/javascript/components/shared/stylings/buttons/ButtonLink.jsx
  app/javascript/components/users/SignIn.jsx
  app/javascript/contexts/auth/AuthProvider.jsx
  app/javascript/main.jsx
Labels: v3

#3392 Minor changes to forms to match mockups.
  app/javascript/components/forms/SignupForm.jsx
  app/javascript/components/users/SignIn.jsx
  app/javascript/components/users/Signup.jsx
Labels: v3

#3388 Switched to fontawesome
  app/assets/stylesheets/application.bootstrap.scss
  app/javascript/components/rooms/Room.jsx
  app/javascript/components/rooms/RoomCard.jsx
  config/initializers/assets.rb
  package-lock.json
  package.json
  yarn.lock
Labels: v3

#3387 Backend: Added create room capability for authenticated users.
  app/controllers/api/v1/rooms_controller.rb
  config/routes.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3393 Added env variable needed when switching social_uids
  app/controllers/concerns/authenticator.rb
  app/controllers/sessions_controller.rb
  config/application.rb
Labels: v2

#3385 Back-end: Recordings table
  app/controllers/api/v1/recordings_controller.rb
  app/controllers/application_controller.rb
  app/models/format.rb
  app/models/recording.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20220411192122_create_formats.rb
  db/migrate/20220412180711_add_length_visibility_users_to_recordings.rb
  db/schema.rb
  spec/controllers/recordings_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
  spec/factories/format_factory.rb
  spec/factories/recording_factory.rb
  spec/models/format_spec.rb
  spec/models/recording_spec.rb
Labels: v3

#3398 Back-end: Deleting Room
  app/controllers/api/v1/rooms_controller.rb
  config/routes.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3386 Recording table front end
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/recordings.scss
  app/javascript/components/rooms/RecordingsTable.jsx
  app/javascript/helpers/Axios.jsx
  app/javascript/hooks/queries/recordings/useRecordings.jsx
Labels: v3

#3397 Cleaned up a bunch of styling and fixed the nav tabs and background
  app/assets/builds/.keep
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/custom_helpers.scss
  app/assets/stylesheets/helpers.scss
  app/assets/stylesheets/variables.scss
  app/javascript/App.jsx
  app/javascript/components/home_page/HomePage.jsx
  app/javascript/components/rooms/Presentation.jsx
  app/javascript/components/rooms/RecordingsTable.jsx
  app/javascript/components/rooms/Room.jsx
  app/javascript/components/rooms/RoomSettings.jsx
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/components/rooms/SharedAccess.jsx
  app/javascript/components/shared/Header.jsx
  app/javascript/components/users/SignIn.jsx
  app/javascript/components/users/Signup.jsx
  app/javascript/main.jsx
Labels: v3

#3399 Delete room front end
  app/javascript/components/rooms/Room.jsx
  app/javascript/hooks/mutations/rooms/useDeleteRoom.jsx
Labels: v3

#3400 Frontend: Minor improvement.
  app/javascript/components/shared/stylings/Spinner.jsx
Labels: v3

#3402 Backend: Adding dependent assertion to relevant model specs.
  spec/models/recording_spec.rb
  spec/models/room_spec.rb
  spec/models/user_spec.rb
Labels: v3

#3403 Importing recordings scss
  app/assets/stylesheets/application.bootstrap.scss
Labels: v3

#3394 Create room feature
  app/javascript/components/rooms/RoomCard.jsx
  app/javascript/components/rooms/RoomPlaceHolder.jsx
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/helpers/Axios.jsx
  app/javascript/hooks/mutations/rooms/useCreateRoom.jsx
Labels: v3

#3395 Backend: Add User Update Name Form
  app/controllers/api/v1/users_controller.rb
  app/models/user.rb
  config/routes.rb
  spec/controllers/users_controller_spec.rb
  spec/models/user_spec.rb
Labels: v3

#3401 Backend: Designed the models for room settings and meeting options.
  app/models/meeting_option.rb
  app/models/room.rb
  app/models/room_meeting_option.rb
  db/migrate/20220418171035_create_meeting_options.rb
  db/migrate/20220418171152_create_room_meeting_options.rb
  db/schema.rb
  spec/models/meeting_option_spec.rb
  spec/models/room_meeting_option_spec.rb
Labels: v3

#3396 Frontend: Add User Update Name Form
  app/javascript/components/forms/FormControl.jsx
  app/javascript/components/forms/UpdateUserForm.jsx
  app/javascript/components/shared/Header.jsx
  app/javascript/components/users/Profile.jsx
  app/javascript/contexts/auth/AuthProvider.jsx
  app/javascript/helpers/forms/UpdateUserFormHelpers.jsx
  app/javascript/hooks/mutations/users/useUpdateUser.jsx
  app/javascript/main.jsx
Labels: v3

#3404 Backend: Add Delete User Form
  app/controllers/api/v1/users_controller.rb
  config/routes.rb
  spec/controllers/users_controller_spec.rb
Labels: v3

#3405 Frontend: Add Delete User Form
  app/javascript/components/forms/DeleteUserForm.jsx
  app/javascript/components/shared/Modal.jsx
  app/javascript/components/users/Profile.jsx
  app/javascript/hooks/mutations/users/useDeleteUser.jsx
Labels: v3

#3409 Back-end: Room Recordings List
  app/controllers/api/v1/rooms_controller.rb
  config/routes.rb
  spec/controllers/rooms_controller_spec.rb
  spec/factories/recording_factory.rb
Labels: v3

#3407 Search rooms by name
  app/assets/stylesheets/rooms.scss
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/hooks/queries/rooms/useRooms.jsx
Labels: v3

#3408 Backend: Populated the meeting options table.
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/models/meeting_option.rb
  db/data/20220421162907_populate_meeting_options.rb
  db/data_schema.rb
  db/schema.rb
  spec/models/meeting_option_spec.rb
Labels: v3

#3410 Recording room list front end
  app/javascript/components/recordings/Recordings.jsx
  app/javascript/components/recordings/RoomRecordings.jsx
  app/javascript/components/rooms/FeatureTabs.jsx
  app/javascript/components/rooms/RoomsTabs.jsx
  app/javascript/helpers/Axios.jsx
  app/javascript/hooks/queries/recordings/useRoomRecordings.jsx
Labels: v3

#3424 Added create room modal
  app/javascript/components/forms/CreateRoomForm.jsx
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/components/shared/CreateRoomModal.jsx
  app/javascript/helpers/forms/CreateRoomFormHelpers.jsx
  app/javascript/hooks/mutations/rooms/useCreateRoom.jsx
  app/models/room.rb
  app/services/big_blue_button_api.rb
  spec/factories/meeting_option_factory.rb
  spec/models/room_spec.rb
  spec/services/big_blue_button_api_spec.rb
Labels: on hold, v3

#3417 Backend: Add Avatar Form/Feature
  app/assets/images/default-avatar.png
  app/controllers/api/v1/sessions_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20220421185735_create_active_storage_tables.active_storage.rb
  db/schema.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/avatar_factory.rb
  spec/fixtures/files/default-avatar.png
  spec/fixtures/files/default-pdf.pdf
  spec/fixtures/files/large-avatar.jpg
Labels: v3

#3425 Frontend: Hot patch to dismiss the create room modal.
  app/javascript/components/forms/CreateRoomForm.jsx
  app/javascript/hooks/mutations/rooms/useCreateRoom.jsx
Labels: v3

#3427 Sign up redirect
  app/controllers/api/v1/recordings_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/javascript/hooks/mutations/users/useCreateUser.jsx
Labels: v3

#3414 Frontend: Add Avatar Form/Feature
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/profile.scss
  app/assets/stylesheets/variables.scss
  app/javascript/components/forms/AvatarForm.jsx
  app/javascript/components/forms/DeleteAvatarForm.jsx
  app/javascript/components/shared/Header.jsx
  app/javascript/components/users/AccountInfo.jsx
  app/javascript/components/users/Avatar.jsx
  app/javascript/components/users/Profile.jsx
  app/javascript/components/users/SetAvatar.jsx
  app/javascript/contexts/auth/AuthProvider.jsx
  app/javascript/helpers/forms/AvatarFormHelpers.jsx
  app/javascript/hooks/mutations/users/useCreateAvatar.jsx
  app/javascript/hooks/mutations/users/useDeleteAvatar.jsx
Labels: v3

#3418 Frontend: New Profile Layout
  app/javascript/components/forms/UpdateUserForm.jsx
  app/javascript/components/users/DeleteAccount.jsx
  app/javascript/components/users/Profile.jsx
  app/javascript/helpers/forms/UpdateUserFormHelpers.jsx
Labels: v3

#3429 Fix: Profile
  app/assets/stylesheets/profile.scss
  app/javascript/hooks/mutations/users/useCreateAvatar.jsx
  app/javascript/hooks/mutations/users/useDeleteAvatar.jsx
Labels: v3

#3430 Added missing text from schema
  db/schema.rb
Labels: v3

#3431 Cleaned up
  app/assets/stylesheets/helpers.scss
  app/javascript/components/recordings/Recordings.jsx
  app/javascript/components/recordings/RoomRecordings.jsx
  app/javascript/components/rooms/RoomSettings.jsx
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/components/users/Profile.jsx
Labels: v3
