Repository bigbluebutton/greenlight, pull requests merged in 2022-10, with the labels that each got.

#3949 Adding roomLimit permission
  db/data/20220930022007_populate_room_limit_role_permission.rb
  db/data_schema.rb
Labels: v3

#3952 Solve nil session_token
  app/models/user.rb
  spec/factories/user_factory.rb
  spec/models/user_spec.rb
Labels: v3

#3954 Add Admin/ServerRooms sorting
  app/controllers/api/v1/admin/server_rooms_controller.rb
  app/javascript/components/admin/server_rooms/ServerRoomRow.jsx
  app/javascript/components/admin/server_rooms/ServerRooms.jsx
  app/javascript/hooks/queries/admin/server_rooms/useActiveServerRooms.jsx
  app/javascript/hooks/queries/admin/server_rooms/useServerRooms.jsx
  app/serializers/server_room_serializer.rb
  public/locales/en.json
  spec/controllers/admin/server_rooms_controller_spec.rb
Labels: v3

#3957 Recordings re-sync: Migrated `Admin::ServerRecordingsController#resync` API to `Admin::ServerRoomsController#resync`.
  app/controllers/api/v1/admin/server_recordings_controller.rb
  app/controllers/api/v1/admin/server_rooms_controller.rb
  app/services/recordings_sync.rb
  config/routes.rb
  spec/controllers/admin/server_recordings_controller_spec.rb
  spec/controllers/admin/server_rooms_controller_spec.rb
  spec/services/recordings_sync_spec.rb
Labels: v3

#3961 Reintroduce csrf
  app/controllers/api/v1/sessions_controller.rb
  app/controllers/application_controller.rb
  app/controllers/external_controller.rb
  app/javascript/helpers/Axios.jsx
Labels: v3

#3953 Rooms: Updated the Rooms UI to use `RoomsController#index` search capability
  app/controllers/api/v1/admin/server_rooms_controller.rb
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/hooks/mutations/rooms/useCreateRoom.jsx
  app/javascript/hooks/queries/rooms/useRooms.jsx
Labels: v3

#3955 Add Admin/ManageUsers sorting
  app/controllers/api/v1/admin/users_controller.rb
  app/javascript/components/admin/manage_users/ManageUserRow.jsx
  app/javascript/components/admin/manage_users/ManageUsersTable.jsx
  app/javascript/hooks/queries/admin/manage_users/useActiveUsers.jsx
  app/models/user.rb
Labels: v3

#3950 Added ResyncOnLogin Site Setting
  app/controllers/external_controller.rb
  app/javascript/components/admin/site_settings/SettingsRow.jsx
  app/javascript/components/admin/site_settings/registration/Registration.jsx
  app/javascript/components/admin/site_settings/settings/Settings.jsx
  db/data/20220929144051_add_resync_on_login_to_settings.rb
  public/locales/en.json
  spec/controllers/external_controller_spec.rb
Labels: v3

#3966 Query cache: Minor fix to `useRoom` & `useRoomRecordings` queries.
  app/javascript/hooks/mutations/recordings/useDeleteRecording.jsx
  app/javascript/hooks/mutations/rooms/useDeletePresentation.jsx
  app/javascript/hooks/mutations/rooms/useUpdateRoom.jsx
  app/javascript/hooks/mutations/rooms/useUploadPresentation.jsx
  app/javascript/hooks/queries/recordings/useRoomRecordings.jsx
  app/javascript/hooks/queries/rooms/useRoom.jsx
Labels: v3

#3941 UI/UX: Added `DefaultErrorPage` and set a top level error boundary.
  app/assets/stylesheets/application.bootstrap.scss
  app/javascript/components/errors/DefaultErrorPage.jsx
  app/javascript/main.jsx
  public/locales/en.json
Labels: v3

#3969 Minor fix to failed eslint checks.
  app/javascript/components/home/HomePage.jsx
  app/javascript/components/rooms/room/FeatureTabs.jsx
Labels: v3

#3970 Fix Join Meeting layout
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/helpers.scss
  app/controllers/api/v1/rooms_controller.rb
  app/javascript/components/rooms/room/RoomJoin.jsx
  app/javascript/hooks/queries/rooms/useRoom.jsx
  app/serializers/current_room_serializer.rb
  app/serializers/public_room_serializer.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3967 VerifyAccountController: Added AuthZ checks to `#create`.
  app/controllers/api/v1/verify_account_controller.rb
  spec/controllers/verify_account_controller_spec.rb
Labels: v3

#3980 V2 Resources Migration: Defined the migrations APIs structure.
  app/controllers/api/v1/migrations/external_controller.rb
  spec/controllers/migrations/external_controller_spec.rb
Labels: v3

#3982 V2 roles migration: Added `Migrations::create_role` API.
  app/controllers/api/v1/migrations/external_controller.rb
  config/routes.rb
Labels: v3

#3979 Change Shared By layout (small design fix)
  app/javascript/components/rooms/RoomCard.jsx
  public/locales/en.json
Labels: v3

#3981 Add GG Spinner
  app/assets/stylesheets/application.bootstrap.scss
  app/javascript/components/rooms/room/RoomJoin.jsx
  app/javascript/components/shared_components/utilities/GGSpinner.jsx
Labels: v3

#3962 Add DefaultRole SiteSetting
  app/controllers/api/v1/users_controller.rb
  app/controllers/application_controller.rb
  app/controllers/external_controller.rb
  app/javascript/components/admin/site_settings/registration/Registration.jsx
  app/javascript/components/admin/site_settings/settings/SettingSelect.jsx
  app/services/user_creator.rb
  db/data/20221003201116_populate_default_role_settings.rb
  public/locales/en.json
  spec/controllers/external_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/requests/users_controller_spec.rb
  spec/services/user_creator_spec.rb
Labels: v3

#3974 Add undeletable roles
  app/controllers/api/v1/admin/roles_controller.rb
  app/javascript/components/admin/roles/forms/DeleteRoleForm.jsx
  app/javascript/components/admin/roles/forms/EditRoleForm.jsx
  app/javascript/hooks/mutations/admin/roles/useDeleteRole.jsx
  public/locales/en.json
  spec/controllers/admin/roles_controller_spec.rb
Labels: v3

#3989 Fix Shared Users join as Moderators
  app/controllers/api/v1/meetings_controller.rb
  spec/controllers/meetings_controller_spec.rb
Labels: v3

#3987 V2 Resources Migration: Added `Migrations::create_role` specs.
  spec/controllers/migrations/external_controller_spec.rb
Labels: v3

#3977 Change flow of require authentication
  app/controllers/external_controller.rb
  app/javascript/components/rooms/room/join/RequireAuthentication.jsx
  app/javascript/components/rooms/room/join/RoomJoin.jsx
  app/javascript/hooks/mutations/sessions/useCreateSession.jsx
  app/javascript/hooks/mutations/users/useCreateUser.jsx
  app/javascript/main.jsx
  public/locales/en.json
  spec/controllers/external_controller_spec.rb
Labels: v3

#3956 RoomLimit - Front end + validations
  app/assets/stylesheets/admin_panel.scss
  app/javascript/components/admin/roles/forms/EditRoleForm.jsx
  app/javascript/helpers/forms/EditRoleFormHelpers.jsx
Labels: v3

#3992 Fix User join his own room as a moderator
  app/controllers/api/v1/meetings_controller.rb
  spec/controllers/meetings_controller_spec.rb
Labels: v3

#3993 Improve Rooms query
  app/controllers/api/v1/rooms_controller.rb
Labels: v3

#3975 Add new UserBoard icon
  app/assets/stylesheets/rooms.scss
  app/javascript/components/rooms/MeetingBadges.jsx
  app/javascript/components/rooms/RoomCard.jsx
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/components/rooms/UserBoardIcon.jsx
  app/javascript/components/rooms/room/Room.jsx
  app/serializers/current_room_serializer.rb
Labels: v3

#3997 Small layout fix for rooms
  app/assets/stylesheets/rooms.scss
  app/javascript/components/rooms/RoomsList.jsx
Labels: v3

#4002 Minor improvements everywhere
  app/controllers/application_controller.rb
  app/controllers/external_controller.rb
  app/javascript/components/admin/manage_users/ManageUserRow.jsx
  app/javascript/components/admin/manage_users/ManageUsersTable.jsx
  app/javascript/components/rooms/room/join/RoomJoin.jsx
  app/serializers/public_room_serializer.rb
  app/services/meeting_starter.rb
  db/data_schema.rb
  spec/controllers/external_controller_spec.rb
  spec/services/meeting_starter_spec.rb
Labels: v3

#3998 Fix Rooms sorting (NULLS FIRST is the default for DESC)
  app/controllers/api/v1/rooms_controller.rb
  app/serializers/room_serializer.rb
Labels: v3

#3995 V2 Resources Migration: Optimized `decrypted_params` using memoization.
  app/controllers/api/v1/migrations/external_controller.rb
Labels: on hold, v3

#4001 Resources migrations: Added `migrations:roles` task.
  config/application.rb
  lib/tasks/migrations/migrations.rake
  sample.env
Labels: v2

#4007 Admin Panel fixes
  app/assets/stylesheets/admin_panel.scss
  app/javascript/components/admin/site_settings/SiteSettings.jsx
  config/initializers/pagy.rb
Labels: v3

#3996 V2 Resources Migration: Adding `Migrations::ExternalController#create_user` specs.
  .rubocop.yml
  spec/controllers/migrations/external_controller_spec.rb
Labels: v3

#4009 Resources migration: Added `migrations:users` task.
  lib/tasks/migrations/migrations.rake
Labels: v2

#4003 Add Shared Access search restriction (3 characters) + add scrollbar
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/shared_accesses.scss
  app/controllers/api/v1/shared_accesses_controller.rb
  app/javascript/components/rooms/room/shared_access/forms/SharedAccessForm.jsx
  app/javascript/hooks/queries/shared_accesses/useShareableUsers.jsx
  public/locales/en.json
  spec/controllers/shared_accesses_controller_spec.rb
Labels: v3

#4008 V2 Resources Migration: Fixed `Migrations::ExternalController#create_user`to generate password only for local users.
  app/controllers/api/v1/migrations/external_controller.rb
  spec/controllers/migrations/external_controller_spec.rb
Labels: v3

#4010 Resources migration: Enabled migration tasks with batch processing.
  lib/tasks/migrations/migrations.rake
Labels: v2

#4017 Initial setup for registration method
  app/javascript/components/admin/manage_users/ManageUsers.jsx
  app/javascript/components/admin/site_settings/SiteSettings.jsx
  app/javascript/components/admin/site_settings/registration/Registration.jsx
  app/javascript/components/admin/site_settings/settings/SettingSelect.jsx
  app/models/invitation.rb
  db/migrate/20221019201841_create_invitations.rb
  db/schema.rb
  public/locales/en.json
  spec/controllers/users_controller_spec.rb
  spec/factories/invitation_factory.rb
  spec/models/invitation_spec.rb
  spec/requests/users_controller_spec.rb
Labels: v3

#4021 Added invite logic for local sign in
  app/controllers/api/v1/users_controller.rb
  app/javascript/components/home/HomePage.jsx
  app/javascript/components/users/authentication/Signup.jsx
  app/javascript/hooks/mutations/users/useCreateUser.jsx
  app/models/invitation.rb
  public/locales/en.json
  spec/controllers/users_controller_spec.rb
  spec/models/invitation_spec.rb
Labels: v3

#4022 Fix Create User from Admin panel wording
  app/javascript/components/admin/manage_users/ManageUsers.jsx
  app/javascript/components/admin/manage_users/forms/UserSignupForm.jsx
  app/javascript/helpers/forms/SignupFormHelpers.jsx
  public/locales/en.json
Labels: v3

#4004 Add Recordings count badge
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/recordings.scss
  app/controllers/api/v1/recordings_controller.rb
  app/javascript/components/recordings/RecordingsCountTab.jsx
  app/javascript/components/rooms/Rooms.jsx
  app/javascript/hooks/mutations/recordings/useDeleteRecording.jsx
  app/javascript/hooks/queries/recordings/useRecordingsCount.jsx
  config/routes.rb
  spec/controllers/recordings_controller_spec.rb
Labels: v3

#3972 RoomLimit Backend Check
  .rubocop.yml
  app/controllers/api/v1/rooms_controller.rb
  app/controllers/concerns/authorizable.rb
  app/javascript/hooks/mutations/admin/manage_users/useCreateServerRoom.jsx
  app/javascript/hooks/mutations/rooms/useCreateRoom.jsx
  app/services/permissions_checker.rb
  public/locales/en.json
  spec/controllers/rooms_controller_spec.rb
  spec/factories/user_factory.rb
Labels: v3

#4026 Add Debouncing to SearchBarQuery
  app/javascript/components/admin/manage_users/ActiveUsers.jsx
  app/javascript/components/admin/manage_users/ManageUsers.jsx
  app/javascript/components/admin/roles/Roles.jsx
  app/javascript/components/admin/server_recordings/ServerRecordings.jsx
  app/javascript/components/admin/server_rooms/ServerRooms.jsx
  app/javascript/components/recordings/Recordings.jsx
  app/javascript/components/recordings/room_recordings/RoomRecordings.jsx
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/components/rooms/room/shared_access/SharedAccess.jsx
  app/javascript/components/rooms/room/shared_access/SharedAccessList.jsx
  app/javascript/components/rooms/room/shared_access/forms/SharedAccessForm.jsx
  app/javascript/components/shared_components/search/SearchBar.jsx
  app/javascript/components/shared_components/search/SearchBarQuery.jsx
  package.json
Labels: v3

#4025 Recordings table; Searching all columns
  app/controllers/api/v1/admin/server_recordings_controller.rb
  app/controllers/api/v1/recordings_controller.rb
  app/models/recording.rb
  spec/controllers/recordings_controller_spec.rb
  spec/factories/recording_factory.rb
Labels: v3

#4014 V2 roles migration: Added `Migrations::create_room` API + specs
  app/controllers/api/v1/migrations/external_controller.rb
  config/routes.rb
  spec/controllers/migrations/external_controller_spec.rb
Labels: v3

#4028 Adding status column to user model
  app/controllers/api/v1/verify_account_controller.rb
  app/javascript/contexts/auth/AuthProvider.jsx
  app/models/user.rb
  app/serializers/user_serializer.rb
  config/application.rb
  db/migrate/20221025184305_add_status_to_users.rb
  db/schema.rb
  spec/controllers/users_controller_spec.rb
  spec/controllers/verify_account_controller_spec.rb
  spec/factories/user_factory.rb
  spec/models/user_spec.rb
Labels: v3

#4027 Added more invitation stuff
  app/assets/stylesheets/application.bootstrap.scss
  app/controllers/api/v1/admin/invitations_controller.rb
  app/javascript/components/admin/manage_users/ManageUsers.jsx
  app/javascript/components/admin/manage_users/forms/InviteUserForm.jsx
  app/javascript/components/rooms/room/Room.jsx
  app/javascript/helpers/forms/CreateInvitationHelpers.jsx
  app/javascript/hooks/mutations/admin/manage_users/useCreateInvitation.jsx
  app/mailers/user_mailer.rb
  app/views/user_mailer/invitation_email.html.erb
  app/views/user_mailer/invitation_email.text.erb
  config/routes.rb
  public/locales/en.json
  spec/controllers/admin/invitations_controller_spec.rb
Labels: v3

#4033 Remove owner_provider from Room migration
  app/controllers/api/v1/migrations/external_controller.rb
Labels: v3

#4034 Fix ManageUsers search
  app/javascript/components/admin/manage_users/ManageUsers.jsx
Labels: v3

#4035 Admin room search columns
  app/controllers/api/v1/admin/server_rooms_controller.rb
  app/models/room.rb
Labels: v3

#4036 Adding email and role column search
  app/models/user.rb
Labels: v3

#4042 Fix Room#create
  app/controllers/api/v1/rooms_controller.rb
Labels: v3

#4029 Add S3
  Gemfile
  config/environments/production.rb
  config/storage.yml
  sample.env
Labels: v3

#4013 Resources migration: Added `migrations:rooms` task
  lib/tasks/migrations/migrations.rake
Labels: v2

#4041 Added pending tab to manage users
  app/controllers/api/v1/admin/users_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/javascript/components/admin/manage_users/InvitedUsers.jsx
  app/javascript/components/admin/manage_users/ManageUsers.jsx
  app/javascript/components/admin/manage_users/PendingUsers.jsx
  app/javascript/hooks/mutations/admin/manage_users/useUpdateUserStatus.jsx
  app/javascript/hooks/queries/admin/manage_users/usePendingUsers.jsx
  config/routes.rb
  spec/controllers/admin/users_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: v3

#4046 Remove pending/denied users rooms from Room migration
  lib/tasks/migrations/migrations.rake
Labels: v3

#4047 Improve Room migration api
  app/controllers/api/v1/migrations/external_controller.rb
Labels: v3

#4049 Fix Error/Missing page layout
  app/javascript/components/errors/DefaultErrorPage.jsx
  app/javascript/components/errors/NotFoundPage.jsx
  public/locales/en.json
Labels: v3

#4050 Fix Migration task error
  lib/tasks/migrations/migrations.rake
Labels: v3, v2

#4048 V2 resources migration: Removed the use of `Rails.configuration` in tasks
  config/application.rb
  lib/tasks/migrations/migrations.rake
Labels: v2
