Repository bigbluebutton/greenlight, pull requests merged in 2022-08, with the labels that each got.

#3723 Add Buttons to Color Picker
  app/assets/stylesheets/admin_panel.scss
  app/javascript/components/admin/site_settings/appearance/BrandColorPopover.jsx
Labels: v3

#3722 Adding created_at to user serializer
  app/serializers/user_serializer.rb
Labels: v3

#3724 Access Codes 1..4: Rectified room access codes to be a regular room setting.
  app/controllers/api/v1/rooms_controller.rb
  app/models/room.rb
  db/data/20220421162907_populate_meeting_options.rb
  db/data/20220721131636_populate_rooms_configurations.rb
  db/migrate/20220613153834_add_viewer_access_code_to_rooms.rb
  db/migrate/20220614193921_add_moderator_access_code_to_rooms.rb
  db/schema.rb
  spec/controllers/meetings_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3726 Rooms Configurations: Added Acces Codes configs.
  app/javascript/components/admin/RoomConfig.jsx
Labels: v3

#3727 Added back CSRF token
  app/controllers/api/v1/api_controller.rb
  app/controllers/external_controller.rb
  app/javascript/helpers/Axios.jsx
Labels: v3

#3713 Room Settings update 1: Added `MeetingOption::get_config_value`.
  app/models/meeting_option.rb
  app/models/room.rb
  spec/models/meeting_option_spec.rb
  spec/models/room_spec.rb
Labels: v3

#3725 Access codes rectification 5: Access Codes: Added required tests to `room_spec`.
  spec/models/room_spec.rb
Labels: v3

#3699 Room Settings 1: Added `RoomSettingsGetter` service.
  app/services/room_settings_getter.rb
  spec/services/room_settings_getter_spec.rb
Labels: v3

#3729 Add PermissionsChecker service
  app/controllers/api/v1/admin/users_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/concerns/authorizable.rb
  app/services/permissions_checker.rb
  spec/controllers/admin/users_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/permission_factory.rb
  spec/factories/role_permission_factory.rb
  spec/services/permissions_checker_spec.rb
Labels: v3

#3705 Meeting starter: Integrated `RoomSettingsGetter` svc in `MeetingStarter`
  .rubocop.yml
  app/controllers/api/v1/meetings_controller.rb
  app/services/meeting_starter.rb
  spec/controllers/meetings_controller_spec.rb
  spec/services/meeting_starter_spec.rb
Labels: v3

#3714 Room Settings update 2: Integrated `MeetingOption::get_config_value` in `RoomSettingsController#update`.
  app/controllers/api/v1/room_settings_controller.rb
  spec/controllers/room_settings_controller_spec.rb
Labels: v3

#3735 Access Codes: Restricted access codes removal and generation for certain configs.
  app/controllers/api/v1/rooms_controller.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3096 GIT-3086: Fixed the sessions persistent active state after a password update (Closes #3086).
  app/controllers/application_controller.rb
  app/controllers/concerns/authenticator.rb
  app/controllers/password_resets_controller.rb
  app/controllers/users_controller.rb
  config/locales/en.yml
  db/migrate/20220119203008_add_last_pwd_update_to_users.rb
  db/schema.rb
Labels: v2

#3645 Git-3086 Tests
  spec/controllers/main_controller_spec.rb
  spec/controllers/password_resets_controller_spec.rb
  spec/controllers/sessions_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: on hold, v2

#3730 ManageRooms Permission
  app/controllers/api/v1/admin/server_rooms_controller.rb
  app/controllers/api/v1/meetings_controller.rb
  app/controllers/api/v1/rooms_controller.rb
  app/javascript/components/admin/AdminNavSideBar.jsx
  spec/controllers/admin/server_rooms_controller_spec.rb
  spec/controllers/meetings_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3716 Meeting starter cleanup
  app/models/meeting_option.rb
  spec/models/meeting_option_spec.rb
Labels: v3

#3760 Importing Pagination css file only
  app/assets/stylesheets/application.bootstrap.scss
Labels: v3

#3756 Remove admin::user#create endpoint duplication
  app/controllers/api/v1/admin/users_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/javascript/hooks/mutations/admin/manage_users/useAdminCreateUser.jsx
  config/routes.rb
  spec/controllers/admin/users_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: v3

#3700 Room Settings 2: Integrated `RoomSettingsGetter` svc in `RoomSettingsController#show` API.
  app/controllers/api/v1/room_settings_controller.rb
  app/javascript/components/rooms/room/room_settings/RoomSettings.jsx
  spec/controllers/room_settings_controller_spec.rb
Labels: v3

#3739 Fix Room Card styling
  app/assets/stylesheets/rooms.scss
  app/assets/stylesheets/variables.scss
  app/javascript/components/rooms/RoomCard.jsx
Labels: v3

#3740 Add Pagination Styling
  app/assets/stylesheets/application.bootstrap.scss
  app/javascript/components/admin/manage_users/ActiveUsers.jsx
  app/javascript/components/admin/manage_users/ManageUsersTable.jsx
  app/javascript/components/admin/server_recordings/ServerRecordings.jsx
  app/javascript/components/admin/server_rooms/ServerRooms.jsx
  app/javascript/components/recordings/Recordings.jsx
  app/javascript/components/recordings/room_recordings/RoomRecordings.jsx
  app/javascript/components/shared_components/Pagination.jsx
  app/javascript/components/shared_components/PaginationPrevButton.jsx
  app/javascript/components/shared_components/Pagy.jsx
Labels: v3

#3763 Initial work on provider changes
  app/controllers/api/v1/admin/rooms_configurations_controller.rb
  app/controllers/api/v1/admin/site_settings_controller.rb
  app/controllers/api/v1/meetings_controller.rb
  app/controllers/api/v1/room_settings_controller.rb
  app/controllers/api/v1/rooms_configurations_controller.rb
  app/controllers/api/v1/rooms_controller.rb
  app/controllers/api/v1/site_settings_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/application_controller.rb
  app/controllers/external_controller.rb
Labels: v3

#3701 Room settings 3: Extended the `RoomSettings` and `RoomSettingsRow` UIs.
  app/javascript/components/rooms/room/room_settings/RoomSettings.jsx
  app/javascript/components/rooms/room/room_settings/RoomSettingsRow.jsx
  app/javascript/hooks/mutations/room_settings/useUpdateRoomSetting.jsx
Labels: v3

#3765 Add named arguments to the ensure_authorized method
  app/controllers/api/v1/users_controller.rb
  app/controllers/concerns/authorizable.rb
  app/services/permissions_checker.rb
  spec/services/permissions_checker_spec.rb
Labels: v3

#3758 Remove admin::create_server_room endpoint duplication
  app/controllers/api/v1/admin/users_controller.rb
  app/controllers/api/v1/rooms_controller.rb
  app/javascript/components/admin/manage_users/ManageUserRow.jsx
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/components/rooms/room/forms/CreateRoomForm.jsx
  app/javascript/helpers/forms/CreateRoomFormHelpers.jsx
  app/javascript/hooks/mutations/admin/manage_users/useCreateServerRoom.jsx
  app/javascript/hooks/mutations/rooms/useCreateRoom.jsx
  spec/controllers/admin/users_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3757 Remove admin::user#destroy endpoint duplication + "admin" specs template proposal
  .rubocop.yml
  app/controllers/api/v1/users_controller.rb
  config/routes.rb
  spec/controllers/users_controller_spec.rb
Labels: v3

#3767 Big refactor related to roles provider
  app/controllers/api/v1/admin/roles_controller.rb
  app/models/role.rb
  app/models/role_permission.rb
  config/application.rb
  config/environments/development.rb
  db/data/20220531182437_populate_roles.rb
  db/data/20220721145933_populate_role_permissions.rb
  db/migrate/20220531180853_create_roles.rb
  db/migrate/20220721144137_create_role_permissions.rb
  db/schema.rb
  spec/controllers/admin/rooms_configurations_controller_spec.rb
  spec/controllers/admin/server_rooms_controller_spec.rb
  spec/controllers/admin/users_controller_spec.rb
  spec/controllers/meetings_controller_spec.rb
  spec/controllers/room_settings_controller_spec.rb
  spec/controllers/rooms_configurations_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/role_factory.rb
  spec/factories/rooms_configuration_factory.rb
  spec/factories/site_setting_factory.rb
  spec/factories/user_factory.rb
  spec/models/role_permission_spec.rb
  spec/models/role_spec.rb
  spec/services/permissions_checker_spec.rb
Labels: v3

#3749 ManageRoles Permission
  app/controllers/api/v1/admin/roles_controller.rb
  app/javascript/components/admin/AdminNavSideBar.jsx
  spec/controllers/admin/roles_controller_spec.rb
Labels: v3

#3766 SharedList Permission
  app/controllers/api/v1/shared_accesses_controller.rb
  spec/controllers/shared_accesses_controller_spec.rb
Labels: v3

#3768 Remove admin::server_rooms#destroy endpoint duplication
  app/controllers/api/v1/admin/server_rooms_controller.rb
  app/controllers/api/v1/rooms_controller.rb
  app/javascript/hooks/mutations/admin/server_rooms/useDeleteServerRoom.jsx
  spec/controllers/admin/server_rooms_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3764 Room settings: Upgraded `RoomSettingsGetter` service.
  app/controllers/api/v1/room_settings_controller.rb
  app/services/room_settings_getter.rb
  spec/controllers/room_settings_controller_spec.rb
  spec/services/room_settings_getter_spec.rb
Labels: v3

#3774 Renamed users column to participants to avoid naming collisions
  app/javascript/components/admin/server_recordings/ServerRecordingRow.jsx
  app/javascript/components/recordings/RecordingRow.jsx
  app/javascript/components/recordings/RecordingsList.jsx
  app/javascript/components/recordings/room_recordings/RoomsRecordingRow.jsx
  app/models/recording.rb
  app/serializers/recording_serializer.rb
  app/services/recording_creator.rb
  db/migrate/20220412180711_add_length_visibility_users_to_recordings.rb
  db/schema.rb
  spec/factories/recording_factory.rb
  spec/models/recording_spec.rb
Labels: v3

#3775 Fix failing tests
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3777 Front end: Minor fix.
  app/javascript/components/recordings/RecordingRow.jsx
Labels: v3

#3776 Room settings: Upgraded `RoomSettingsGetter` to hide access codes values
  app/controllers/api/v1/room_settings_controller.rb
  app/services/room_settings_getter.rb
  spec/controllers/room_settings_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
  spec/services/room_settings_getter_spec.rb
Labels: v3

#3752 MangeRecordings Permission
  app/controllers/api/v1/admin/server_recordings_controller.rb
  app/controllers/api/v1/recordings_controller.rb
  app/javascript/components/admin/AdminNavSideBar.jsx
  app/javascript/hooks/queries/recordings/useRecordingsReSync.jsx
  config/routes.rb
  spec/controllers/admin/server_recordings_controller_spec.rb
  spec/controllers/recordings_controller_spec.rb
Labels: v3

#3778 SiteSettings Permission
  app/controllers/api/v1/admin/site_settings_controller.rb
  spec/controllers/admin/site_settings_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3771 Add default Branding Image
  app/assets/images/bbb_logo.png
  app/services/setting_getter.rb
  db/data/20220713143528_populate_site_settings.rb
Labels: v3

#3779 Fix Spinner UI glitch in Admin tabs
  app/javascript/components/admin/room_configuration/RoomConfig.jsx
  app/javascript/components/admin/site_settings/SiteSettings.jsx
Labels: v3

#3784 Room settings: Upgraded `RoomSettingsGetter` service -> Fetching settings by name ✔️
  app/services/room_settings_getter.rb
  spec/services/room_settings_getter_spec.rb
Labels: v3

#3785 Rooms : Added `RoomsController#public_show` API.
  app/controllers/api/v1/rooms_controller.rb
  app/serializers/public_room_serializer.rb
  config/routes.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3787 Roles spec cleanup
  .rubocop.yml
  spec/controllers/admin/roles_controller_spec.rb
  spec/factories/user_factory.rb
Labels: v3

#3770 Fix Branding Image
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/helpers.scss
  app/javascript/components/admin/site_settings/appearance/Appearance.jsx
  app/javascript/components/admin/site_settings/appearance/BrandColor.jsx
  app/javascript/components/admin/site_settings/appearance/BrandingImage.jsx
  app/javascript/components/shared_components/Header.jsx
  app/javascript/components/shared_components/Logo.jsx
  app/javascript/hooks/mutations/admin/site_settings/useUpdateSiteSetting.jsx
Labels: v3

#3786 Frontend access restrictions for regular users
  app/javascript/components/admin/AdminNavSideBar.jsx
  app/javascript/components/shared_components/Header.jsx
Labels: v3

#3789 Refactor Specs - use of user traits for admin specs
  app/controllers/api/v1/meetings_controller.rb
  spec/controllers/admin/roles_controller_spec.rb
  spec/controllers/admin/server_recordings_controller_spec.rb
  spec/controllers/admin/server_rooms_controller_spec.rb
  spec/controllers/admin/site_settings_controller_spec.rb
  spec/controllers/admin/users_controller_spec.rb
  spec/controllers/meetings_controller_spec.rb
  spec/controllers/recordings_controller_spec.rb
  spec/controllers/rooms_controller_spec.rb
  spec/controllers/shared_accesses_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/user_factory.rb
Labels: v3

#3769 Room settings: Upgraded `RoomSettingsController#update` API.
  .rubocop.yml
  app/controllers/api/v1/room_settings_controller.rb
  spec/controllers/room_settings_controller_spec.rb
Labels: v3

#3796 Admin UX changes
  app/controllers/api/v1/admin/users_controller.rb
  app/javascript/components/admin/AdminNavSideBar.jsx
  app/javascript/components/admin/manage_users/EditUser.jsx
  app/javascript/components/admin/manage_users/ManageUserRow.jsx
  app/javascript/components/admin/roles/EditRole.jsx
  app/javascript/components/admin/roles/RolePill.jsx
  app/javascript/components/admin/roles/RoleRow.jsx
  app/javascript/components/shared_components/Header.jsx
  app/javascript/hooks/mutations/admin/roles/useDeleteRole.jsx
  app/javascript/main.jsx
  app/serializers/server_user_serializer.rb
  app/serializers/user_serializer.rb
Labels: v3

#3797 Adding CanRecord permission
  db/data/20220721145016_populate_permissions.rb
  db/data/20220721145933_populate_role_permissions.rb
Labels: v3

#3799 UI/UX changes
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/helpers.scss
  app/javascript/components/admin/manage_users/EditUser.jsx
  app/javascript/components/admin/manage_users/ManageUsers.jsx
  app/javascript/components/admin/roles/EditRole.jsx
  app/javascript/components/admin/roles/Roles.jsx
  app/javascript/components/admin/room_configuration/RoomConfig.jsx
  app/javascript/components/admin/server_recordings/ServerRecordings.jsx
  app/javascript/components/admin/server_rooms/ServerRooms.jsx
  app/javascript/components/admin/site_settings/SiteSettings.jsx
  app/javascript/components/rooms/RoomCard.jsx
  app/javascript/components/rooms/room/Room.jsx
  app/javascript/components/shared_components/Footer.jsx
  app/javascript/components/shared_components/Header.jsx
  app/javascript/components/users/user/Profile.jsx
Labels: v3

#3772 Room settings: Integrated access codes with `RoomSettingsController` APIs.
  app/javascript/components/rooms/room/room_settings/AccessCodeRow.jsx
  app/javascript/components/rooms/room/room_settings/AccessCodes.jsx
  app/javascript/components/rooms/room/room_settings/RoomSettings.jsx
  app/javascript/components/rooms/room/room_settings/RoomSettingsRow.jsx
Labels: v3

#3798 CanRecord Permission
  app/controllers/api/v1/admin/role_permissions_controller.rb
  app/controllers/api/v1/meetings_controller.rb
  app/controllers/api/v1/room_settings_controller.rb
  app/javascript/components/admin/roles/forms/EditRoleForm.jsx
  app/javascript/components/rooms/room/room_settings/RoomSettings.jsx
  app/javascript/hooks/mutations/admin/role_permissions/useUpdateRolePermissions.jsx
  app/javascript/hooks/queries/admin/role_permissions/useRolePermissions.jsx
  app/services/meeting_starter.rb
  app/services/room_settings_getter.rb
  config/routes.rb
  spec/controllers/meetings_controller_spec.rb
  spec/controllers/room_settings_controller_spec.rb
  spec/factories/user_factory.rb
  spec/services/meeting_starter_spec.rb
  spec/services/room_settings_getter_spec.rb
Labels: v3

#3801 fixed background color
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/helpers.scss
  app/javascript/components/admin/manage_users/EditUser.jsx
  app/javascript/components/admin/manage_users/ManageUsers.jsx
  app/javascript/components/admin/roles/EditRole.jsx
  app/javascript/components/admin/roles/Roles.jsx
  app/javascript/components/admin/room_configuration/RoomConfig.jsx
  app/javascript/components/admin/server_recordings/ServerRecordings.jsx
  app/javascript/components/admin/server_rooms/ServerRooms.jsx
  app/javascript/components/admin/site_settings/SiteSettings.jsx
  app/javascript/components/recordings/Recordings.jsx
  app/javascript/components/recordings/room_recordings/RoomRecordings.jsx
  app/javascript/components/rooms/Rooms.jsx
  app/javascript/components/rooms/RoomsList.jsx
  app/javascript/components/rooms/room/Room.jsx
  app/javascript/components/rooms/room/RoomJoin.jsx
  app/javascript/components/rooms/room/presentation/Presentation.jsx
  app/javascript/components/rooms/room/room_settings/RoomSettings.jsx
  app/javascript/components/rooms/room/shared_access/SharedAccess.jsx
  app/javascript/components/rooms/room/shared_access/SharedAccessEmpty.jsx
  app/javascript/components/rooms/room/shared_access/SharedAccessList.jsx
  app/javascript/components/users/authentication/SignIn.jsx
  app/javascript/components/users/authentication/Signup.jsx
  app/javascript/components/users/password_management/ForgetPassword.jsx
  app/javascript/components/users/password_management/ResetPassword.jsx
  app/javascript/components/users/user/Profile.jsx
Labels: v3

#3782 Added provider filtering
  app/controllers/api/v1/admin/roles_controller.rb
  app/controllers/api/v1/admin/server_recordings_controller.rb
  app/controllers/api/v1/admin/server_rooms_controller.rb
  app/controllers/api/v1/admin/users_controller.rb
  app/controllers/api/v1/shared_accesses_controller.rb
  app/models/recording.rb
  app/models/role.rb
  app/models/room.rb
  app/models/user.rb
  spec/controllers/admin/roles_controller_spec.rb
  spec/controllers/admin/server_recordings_controller_spec.rb
  spec/controllers/admin/server_rooms_controller_spec.rb
  spec/controllers/admin/users_controller_spec.rb
  spec/models/recording_spec.rb
  spec/models/role_spec.rb
  spec/models/room_spec.rb
  spec/models/user_spec.rb
Labels: v3

#3804 Added role editting to profile
  .rubocop.yml
  app/controllers/api/v1/admin/roles_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/javascript/components/users/user/AccountInfo.jsx
  app/javascript/components/users/user/SetAvatar.jsx
  app/javascript/components/users/user/forms/AvatarForm.jsx
  app/javascript/components/users/user/forms/DeleteAvatarForm.jsx
  app/javascript/components/users/user/forms/UpdateUserForm.jsx
  app/javascript/helpers/forms/UpdateUserFormHelpers.jsx
  app/javascript/hooks/mutations/users/useUpdateUser.jsx
  spec/controllers/admin/roles_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: v3

#3788 Join refactoring: First stage of refactoring.
  app/controllers/api/v1/meetings_controller.rb
  app/javascript/channels/rooms_channel.jsx
  app/javascript/components/rooms/room/RoomJoin.jsx
  app/javascript/hooks/queries/rooms/usePublicRoom.jsx
  app/javascript/hooks/queries/rooms/useRoomJoin.jsx
  app/javascript/hooks/queries/rooms/useRoomStatus.jsx
  spec/controllers/meetings_controller_spec.rb
  tmp/pids/.keep
  tmp/storage/.keep
Labels: v3

#3805 Generating a primary color now automatically generates light color
  app/assets/stylesheets/admin_panel.scss
  app/assets/stylesheets/application.bootstrap.scss
  app/javascript/components/admin/room_configuration/RoomConfigRow.jsx
  app/javascript/components/admin/site_settings/appearance/Appearance.jsx
  app/javascript/components/admin/site_settings/appearance/BrandColor.jsx
  app/javascript/components/admin/site_settings/appearance/BrandColorPopover.jsx
  app/javascript/components/admin/site_settings/appearance/BrandingImage.jsx
  app/javascript/hooks/mutations/admin/site_settings/useUpdateSiteSetting.jsx
  package-lock.json
  package.json
  yarn.lock
Labels: v3

#3792 Join refactoring: Changed `MeetingsController#status` API to an HTTP POST endpoint.
  app/controllers/api/v1/meetings_controller.rb
  app/javascript/components/admin/server_rooms/ServerRoomRow.jsx
  app/javascript/components/rooms/room/RoomJoin.jsx
  app/javascript/hooks/mutations/rooms/useRoomStatus.jsx
  app/javascript/hooks/queries/rooms/useRoomStatus.jsx
  config/routes.rb
  spec/controllers/meetings_controller_spec.rb
Labels: v3

#3793 Join refactoring: Removed deprecated `MeetingsController#join` API.
  app/controllers/api/v1/meetings_controller.rb
  config/routes.rb
  spec/controllers/meetings_controller_spec.rb
Labels: v3

#3809 Fix Avatar shape
  app/controllers/api/v1/users_controller.rb
Labels: v3

#3808 Replaced ids with uuids
  app/models/application_record.rb
  db/migrate/20220229174948_enable_uuid.rb
  db/migrate/20220314184634_create_users.rb
  db/migrate/20220315151617_create_rooms.rb
  db/migrate/20220317142349_create_recordings.rb
  db/migrate/20220411192122_create_formats.rb
  db/migrate/20220418171035_create_meeting_options.rb
  db/migrate/20220418171152_create_room_meeting_options.rb
  db/migrate/20220421185735_create_active_storage_tables.active_storage.rb
  db/migrate/20220505192018_create_shared_accesses.rb
  db/migrate/20220531180853_create_roles.rb
  db/migrate/20220531182239_add_role_id_to_users.rb
  db/migrate/20220712202439_create_settings.rb
  db/migrate/20220713143235_create_site_settings.rb
  db/migrate/20220721131241_create_rooms_configurations.rb
  db/migrate/20220721143652_create_permissions.rb
  db/migrate/20220721144137_create_role_permissions.rb
  db/schema.rb
  spec/models/rooms_configuration_spec.rb
Labels: v3

#3811 CanRecord permission rspec
  app/controllers/api/v1/admin/role_permissions_controller.rb
  spec/controllers/admin/role_permissions_controller_spec.rb
  spec/factories/user_factory.rb
  spec/services/room_settings_getter_spec.rb
Labels: v3

#3812 Extended permission checker to take array of names
  app/controllers/api/v1/admin/roles_controller.rb
  app/controllers/concerns/authorizable.rb
  app/javascript/components/users/user/forms/UpdateUserForm.jsx
  app/javascript/hooks/queries/admin/roles/useRoles.jsx
  app/services/permissions_checker.rb
  spec/controllers/admin/roles_controller_spec.rb
  spec/services/permissions_checker_spec.rb
Labels: v3

#3814 Clear out proptype errors
  app/javascript/components/admin/manage_users/ManageUserRow.jsx
  app/javascript/components/admin/manage_users/ManageUsersTable.jsx
  app/javascript/components/admin/manage_users/forms/DeleteUserForm.jsx
  app/javascript/components/admin/roles/RoleRow.jsx
  app/javascript/components/admin/roles/RolesList.jsx
  app/javascript/components/admin/roles/forms/DeleteRoleForm.jsx
  app/javascript/components/admin/roles/forms/EditRoleForm.jsx
  app/javascript/components/admin/server_recordings/ServerRecordingRow.jsx
  app/javascript/components/recordings/RecordingRow.jsx
  app/javascript/components/recordings/RecordingsList.jsx
  app/javascript/components/recordings/room_recordings/RoomsRecordingRow.jsx
  app/javascript/components/rooms/RoomCard.jsx
  app/javascript/components/rooms/room/shared_access/SharedAccessList.jsx
  app/javascript/components/users/user/AccountInfo.jsx
  app/javascript/components/users/user/SetAvatar.jsx
  app/javascript/components/users/user/forms/AvatarForm.jsx
  app/javascript/components/users/user/forms/DeleteAvatarForm.jsx
  app/javascript/components/users/user/forms/UpdateUserForm.jsx
  app/javascript/contexts/auth/AuthProvider.jsx
Labels: v3

#3794 Join refactoring: `RoomSettingsGetter` svc integration in `MeetingsController#status` API.
  app/controllers/api/v1/meetings_controller.rb
  app/services/room_settings_getter.rb
  spec/controllers/meetings_controller_spec.rb
Labels: v3

#3817 Re-structure EditRoles
  app/javascript/components/admin/roles/forms/EditRoleForm.jsx
  app/javascript/helpers/forms/EditRoleFormHelpers.jsx
Labels: v3
