Repository bigbluebutton/greenlight, pull requests merged in 2022-05, with the labels that each got.

#3432 Fixed issue that allowed viewing all users in shared access modal
  app/controllers/users_controller.rb
Labels: bug, security

#3433 Upgraded Rails to 5.2.7.1
  Gemfile
  Gemfile.lock
Labels: security

#3434 Reverted backend to create room modal
  app/models/room.rb
  app/services/big_blue_button_api.rb
  spec/factories/meeting_option_factory.rb
  spec/models/room_spec.rb
  spec/services/big_blue_button_api_spec.rb
Labels: v3

#3436 n+1 recording formats
  app/controllers/api/v1/recordings_controller.rb
Labels: v3

#3435 Auto create meeting options for each room
  app/models/room.rb
  spec/factories/meeting_option_factory.rb
  spec/models/room_spec.rb
Labels: v3

#3440 Added the full joining functionality
  .rubocop.yml
  app/controllers/api/v1/rooms_controller.rb
  app/javascript/channels/rooms_channel.jsx
  app/javascript/components/rooms/RoomJoin.jsx
  app/javascript/components/shared/stylings/Spinner.jsx
  app/javascript/hooks/queries/rooms/useRoomJoin.jsx
  app/javascript/hooks/queries/rooms/useRoomStatus.jsx
  app/services/big_blue_button_api.rb
  config/routes.rb
  spec/controllers/rooms_controller_spec.rb
Labels: v3

#3443 Added a toggle for the mute on join room setting
  app/controllers/api/v1/room_settings_controller.rb
  app/javascript/components/rooms/FeatureTabs.jsx
  app/javascript/components/rooms/RoomSettings.jsx
  app/javascript/hooks/mutations/room_settings/useUpdateRoomSetting.jsx
  config/routes.rb
Labels: v3

#3441 Back-end: Recordings Re-Sync
  .rubocop.yml
  app/controllers/api/v1/recordings_controller.rb
  app/services/big_blue_button_api.rb
  app/services/recordings_sync.rb
  config/routes.rb
  spec/controllers/recordings_controller_spec.rb
  spec/services/big_blue_button_api_spec.rb
  spec/services/recordings_sync_spec.rb
Labels: v3

#3453 Front-end: Recording Re-Sync
  app/javascript/components/recordings/Recordings.jsx
  app/javascript/helpers/Axios.jsx
  app/javascript/hooks/queries/recordings/useRecordingsReSync.jsx
Labels: v3

#3454 Move user_avatar method from User model to Controller/Concerns
  app/controllers/api/v1/sessions_controller.rb
  app/controllers/concerns/avatarable.rb
  app/models/user.rb
Labels: v3

#3456 Allow any user to start meeting
  app/javascript/components/rooms/RoomSettings.jsx
Labels: v3

#3447 Frontend: Add ShareAccess feature (4)
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/helpers.scss
  app/assets/stylesheets/shared_accesses.scss
  app/javascript/components/forms/SharedAccessForm.jsx
  app/javascript/components/forms/UpdateUserForm.jsx
  app/javascript/components/rooms/FeatureTabs.jsx
  app/javascript/components/rooms/SharedAccess.jsx
  app/javascript/components/shared/Modal.jsx
  app/javascript/components/shared_accesses/SharedAccess.jsx
  app/javascript/components/shared_accesses/SharedAccessEmpty.jsx
  app/javascript/components/shared_accesses/SharedAccessList.jsx
  app/javascript/hooks/mutations/shared_accesses/useDeleteSharedAccess.jsx
  app/javascript/hooks/mutations/shared_accesses/useShareAccess.jsx
  app/javascript/hooks/queries/shared_accesses/useShareableUsers.jsx
  app/javascript/hooks/queries/shared_accesses/useSharedUsers.jsx
Labels: v3

#3449 Backend: Add ShareAccess feature (3)
  app/assets/builds/.keep
  app/controllers/api/v1/shared_accesses_controller.rb
  app/models/room.rb
  app/models/shared_access.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20220505192018_create_shared_accesses.rb
  db/schema.rb
  spec/controllers/shared_accesses_controller_spec.rb
  spec/factories/shared_access_factory.rb
Labels: v3

#3461 Delete Recording
  app/controllers/api/v1/recordings_controller.rb
  app/javascript/components/forms/DeleteRecordingForm.jsx
  app/javascript/components/recordings/Recordings.jsx
  app/javascript/hooks/mutations/recordings/useDeleteRecording.jsx
  config/routes.rb
  spec/controllers/recordings_controller_spec.rb
Labels: v3

#3464 Frontend: Add Require Moderator Approval to RoomOptions
  app/javascript/components/rooms/RoomSettings.jsx
  app/javascript/components/rooms/RoomSettingsRow.jsx
  app/javascript/hooks/mutations/room_settings/useUpdateRoomSetting.jsx
  app/javascript/hooks/queries/rooms/useRoomSettings.jsx
Labels: v3

#3465 Frontend: RoomSettings styling
  app/assets/stylesheets/rooms.scss
  app/javascript/components/rooms/FeatureTabs.jsx
  app/javascript/components/rooms/RoomSettings.jsx
  app/javascript/components/rooms/RoomSettingsRow.jsx
Labels: v3

#3469 bbb server recording delete
  app/controllers/api/v1/recordings_controller.rb
  app/services/big_blue_button_api.rb
  spec/controllers/recordings_controller_spec.rb
Labels: v3

#3471 Delete recording on room specific page
  app/javascript/components/forms/DeleteRecordingForm.jsx
  app/javascript/components/recordings/RoomRecordings.jsx
  app/javascript/hooks/mutations/recordings/useDeleteRecording.jsx
Labels: v3

#3472 Cleaning recording deletion
  app/controllers/api/v1/recordings_controller.rb
  app/javascript/components/recordings/Recordings.jsx
  app/javascript/components/recordings/RoomRecordings.jsx
Labels: v3

#3475 hchaptcha installs
  Gemfile
  Gemfile.lock
  package-lock.json
  package.json
  yarn.lock
Labels: v3

#3474 Fix single user issue with SharedAccess
  app/controllers/api/v1/shared_accesses_controller.rb
  app/javascript/components/forms/SharedAccessForm.jsx
  app/javascript/components/shared/SearchBar.jsx
  app/javascript/hooks/mutations/shared_accesses/useShareAccess.jsx
  spec/controllers/shared_accesses_controller_spec.rb
Labels: v3

#3483 hcaptcha signUp
  app/controllers/api/v1/users_controller.rb
  app/javascript/components/forms/SignupForm.jsx
  app/javascript/hooks/mutations/users/useCreateUser.jsx
  config/initializers/hcaptcha.rb
Labels: v3

#3479 Refactored meeting start and implement the room settings in BBB
  app/controllers/api/v1/rooms_controller.rb
  app/models/meeting_option.rb
  app/services/big_blue_button_api.rb
  app/services/meeting_starter.rb
  db/data/20220421162907_populate_meeting_options.rb
  spec/controllers/rooms_controller_spec.rb
  spec/factories/room_meeting_option_factory.rb
  spec/models/meeting_option_spec.rb
  spec/services/big_blue_button_api_spec.rb
  spec/services/meeting_starter_spec.rb
Labels: v3

#3473 Add SearchBarQuery for backend query (1)
  app/assets/stylesheets/application.bootstrap.scss
  app/controllers/api/v1/recordings_controller.rb
  app/javascript/components/recordings/Recordings.jsx
  app/javascript/components/recordings/RecordingsList.jsx
  app/javascript/components/shared/SearchBarQuery.jsx
  app/javascript/helpers/Axios.jsx
  app/javascript/hooks/queries/recordings/useRecordings.jsx
  app/models/recording.rb
  spec/controllers/recordings_controller_spec.rb
  spec/models/recording_spec.rb
Labels: v3

#3476 Implement SearchBarQuery to RoomRecordings
  app/controllers/api/v1/rooms_controller.rb
  app/javascript/components/recordings/RoomRecordings.jsx
  app/javascript/hooks/queries/recordings/useRoomRecordings.jsx
Labels: v3

#3478 Implement SearchBar to RoomsList
  app/assets/stylesheets/rooms.scss
  app/javascript/components/recordings/Recordings.jsx
  app/javascript/components/recordings/RecordingsList.jsx
  app/javascript/components/rooms/RoomsList.jsx
Labels: v3
