Repository bigbluebutton/greenlight, pull requests merged in 2023-06, with the labels that each got.

#5156 Deployment: Fixed pre-upload presentation nginx 413 issue.
  greenlight-v3.nginx
Labels: v3.0.5

#5191 File Uploads: Ensured consistency between FE & BE support types.
  app/assets/locales/en.json
  app/javascript/components/admin/site_settings/appearance/BrandingImage.jsx
  app/javascript/components/rooms/room/presentation/Presentation.jsx
  app/javascript/helpers/FileValidationHelper.jsx
Labels: v3.0.5

#5212 Refactor RoomJoinForm to support translation
  app/assets/locales/en.json
  app/javascript/components/rooms/room/join/RoomJoin.jsx
  app/javascript/helpers/forms/JoinFormHelpers.jsx
  app/javascript/hooks/forms/rooms/useRoomJoinForm.js
Labels: v3

#5190 Site Settings: Add branding image validations
  .licenserc.yaml
  app/controllers/api/v1/admin/site_settings_controller.rb
  app/models/room.rb
  app/models/site_setting.rb
  app/models/user.rb
  config/application.rb
  spec/controllers/admin/site_settings_controller_spec.rb
  spec/fixtures/files/default-avatar.jpg
  spec/fixtures/files/default-avatar.svg
  spec/models/site_setting_spec.rb
Labels: v3.0.5

#4922 Add Provider to v3 migration endpoints
  app/controllers/api/v1/migrations/external_controller.rb
  spec/controllers/migrations/external_controller_spec.rb
Labels: v3

#5219 Added OAuth functionality to MT
  app/controllers/api/v1/admin/tenants_controller.rb
  app/controllers/api/v1/env_controller.rb
  app/controllers/application_controller.rb
  app/javascript/components/home/AuthButtons.jsx
  config/initializers/omniauth.rb
  lib/tasks/admin.rake
Labels: v3.0.5

#5206 Signup: Adding restrictions for edge cases.
  app/controllers/api/v1/api_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/javascript/components/admin/manage_users/ManageUsers.jsx
  app/javascript/components/users/authentication/Signup.jsx
  spec/controllers/users_controller_spec.rb
Labels: v3.0.5

#5197 Fixed bad OmniAuth flow when deployed on a subdirectory (Closes #5176).
  app/controllers/concerns/client_routable.rb
  app/controllers/external_controller.rb
  app/javascript/components/home/AuthButtons.jsx
  app/javascript/components/rooms/room/join/RequireAuthentication.jsx
  app/javascript/components/rooms/room/join/RoomJoin.jsx
  config/application.rb
  esbuild.dev.mjs
  esbuild.mjs
  spec/controllers/external_controller_spec.rb
Labels: v3.0.5

#5220 Added support for protected recordings
  app/controllers/api/v1/recordings_controller.rb
  app/javascript/components/recordings/RecordingRow.jsx
  app/javascript/hooks/mutations/recordings/useCopyRecordingUrl.jsx
  app/javascript/hooks/mutations/recordings/useRedirectRecordingUrl.jsx
  config/routes.rb
  spec/controllers/recordings_controller_spec.rb
Labels: v3.0.5

#5227 Public recordings: Add foundation and structural changes.
  app/controllers/api/v1/recordings_controller.rb
  app/models/recording.rb
  app/services/recording_creator.rb
  spec/controllers/recordings_controller_spec.rb
  spec/factories/recording_factory.rb
  spec/models/recording_spec.rb
Labels: v3.0.5

#5229 Public recordings: Extend `RecordingCreator` service to support public recordings.
  app/services/recording_creator.rb
  spec/services/recording_creator_spec.rb
Labels: v3.0.5

#5243 Filter out health check logs
  config/environments/production.rb
Labels: v3.0.5

#5247 Attempt to fix issue with external accounts
  config/initializers/omniauth.rb
Labels: v3.0.5

#5248 Another attempt at fixing external auth
  config/initializers/omniauth.rb
Labels: v3.0.5

#5249 Fix health check destroying db connections
  app/controllers/health_checks_controller.rb
  lib/tasks/configuration.rake
Labels: v3.0.5

#5237 Added dynamic og titles and room titles
  app/helpers/application_helper.rb
  app/javascript/App.jsx
  app/javascript/components/rooms/room/Room.jsx
  app/javascript/components/rooms/room/join/RoomJoin.jsx
  app/javascript/components/shared_components/utilities/Title.jsx
  app/views/layouts/application.html.erb
  package-lock.json
  package.json
  spec/controllers/health_checks_controller_spec.rb
  yarn.lock
Labels: v3.0.5

#5251 Added back servers recordings sync task
  lib/tasks/servers_recordings_sync.rake
Labels: v3.0.5

#5250 Set optional room configs to default_disabled
  lib/tasks/migrations/migrations.rake
Labels: v3, v2, v3.0.5

#5268 Fix rake task filename typo
  lib/tasks/server_recordings_sync.rake
Labels: v3.0.5

#5266 Fix relative root in Migrations task
  lib/tasks/migrations/migrations.rake
Labels: v2, v3.0.5

#5269 Add add_default_tenant rake task
  app/controllers/api/v1/admin/tenants_controller.rb
  app/services/tenant_setup.rb
  lib/tasks/add_default_tenant.rake
Labels: v3.0.5

#5279 Add "return button" to empty public Recordings
  app/assets/locales/en.json
  app/javascript/components/rooms/room/public_recordings/PublicRecordingsList.jsx
Labels: v3.0.5
